### ISSUE TITLE
Specify number of levels in pyramid file

### ISSUE THREAD

**Issue by ahankinson** [libvips/libvips#1]
Hi,

I am using VIPS to create pyramid TIFF files of multi-page books. We're finding that VIPS will try to automatically determine how many pyramid levels should go in a given PTIF file, but this means that we're finding pages where some images are processed into 4 discrete levels, while others are processed into five.

For example, a TIFF file that is 1396x2114 will be processed to five pyramid levels, while a slightly smaller image (1411x2046) is processed into four pyramid levels.

We're using the following command to process these images:

vips im_vips2tiff $infile $outfile.tiff:jpeg:75,tile:256x256,pyramid

Is there any way to force an output pyramid file to contain a fixed number of levels?

Thanks.

**Comment by gvincke** [comment]
Hi.
I have the same question, but for others reasons.
I want to create a PTIFF from an image of 540k x 4k pixels, and with tiles of 256x256.
I use this command in my terminal (Debian) to do so :
`vips tiffsave --vips-progress --vips-leak input.v output.tiff --tile --pyramid --compression jpeg -Q 95 --tile-width 256 --tile-height 256 --bigtiff`
This command works very well for large ranges of images, but for this one it does not and just say : 
`VipsRegion: valid clipped to nothing`
As i understood it's because the ratio does not allow to create the last tile of 256 pixels width and less than 2 pixels height. So due to this ratio, which only apply to the summit of the pyramid, vips refuse to create my PTIFF.
So my question is : As my interest focus mainly on the biggest layers, is there a manner to specify that we want vips to create the PTIFF and ignore the last or n lasts layers ? Because here i know that vips is able to do quite a pyramid, but it refuse just due to the last tile, wich i don't care.
Thanks a lot for your answer.
Have a nice day.

**Comment by gvincke** [comment]
Sure.
