### ISSUE TITLE
Question: Applying 3D LUT to images for colour grading

### ISSUE THREAD

**Issue by roborourke** [libvips/libvips#1153]
Apologies if this is answered somewhere I’ve just been struggling to find examples. I’m trying to find a good way to apply 3D LUTs to images for colour grading.

I can get .cube files and various other formats including hald images reasonably easily but I haven’t work out how to use them with libvips yet. Experiments using maplut haven’t worked the way I’d hoped.

Would I be better off converting the LUT to icm format or similar? And then use vips_icc_transform()?

**Comment by jcupitt** [comment]
Hello, yes, libvips only really supports simple array-style LUTs directly.

I agree, making a profile and running it through lcms with vips_icc_transform() sounds like it might work. I've not tried though.

**Comment by roborourke** [comment]
I've tried a bit with `vips_icc_transform()` now but it doesn't appear to modify the output image at all with an `.icm` file I got from lutify.me, think I'm missing a step or just not understanding how icc profiles work which is highly likely!

**Comment by jcupitt** [comment]
I don't know much about sharp, but at the command-line you'd do something like:

```
$ vips icc_transform Gugg_coloured.jpg x.jpg[strip] /usr/share/color/icc/colord/AdobeRGB1998.icc --input-profile /usr/share/color/icc/colord/sRGB.icc 
```

To get:

![y](https://user-images.githubusercontent.com/580843/47926628-f0cb3c80-deb8-11e8-8e86-21a8dc864007.jpg)

(original on the left)

The input image is untagged, so `--input-profile` sets that as sRGB. It uses Adobe 98 (a wide gamut profile) as the target. Because Adobe 98 is a wide gamut, when you map pixels, they move towards the neutral axis and appear less saturated. 

The `[strip]` makes sure the output image does not have the Adobe98 profile attached. If you leave it on, then your display program will use inverse lookup to approximate the original image and it will appear not to have changed.

**Comment by felixbuenemann** [comment]
The `strip` option removes the embedded icc profile when saving the file.

Often this is used to reduce file size, since most files are using sRGB interpretation anyways, so there's no need to embed the sRGB.icc.

For example, if you generate a JPEG for display on the web and your source image is a JPEG with AdobeRGB profile, you could do the following:

```
$ vips icc_transform input.jpg output.jpg[strip] sRGB.icc --embedded
```

This way it would convert the pixel values from the embedded AdobeRGB profile to sRGB and then throw away the profile.

If you would just do:

```
$ vips copy input.jpg output.jpg[strip]
```

It would strip the AdobeRGB profile, which would lead to wrong colors, since the image would now be interpreted as sRGB while the pixel values are still the same as before.

**Comment by jcupitt** [comment]
I'll close. Please reopen if this is still an issue.
