### ISSUE TITLE
Skip fully white tiles when creating Deep Zoom pyramids (not Google format)

### ISSUE THREAD

**Issue by bverem** [libvips/libvips#1185]
Opened new issue at the request of @jcupitt #352

White tiles are currently not saved when passing the `--layout google` option to `dzsave`. I'm curious to see if this can be done when saving as .dzi, which I've started using in lieu of the Google format because navigating slides is a bit quicker (less waiting for tiles to load). Even when using a 512px tile size, whole slide microscopy images converted to .dzi are still pretty unwieldy, and much of it is white space (especially in [biopsy specimens](https://imgur.com/XENOBtE)). Given the workflow of how these images are uploaded into our homegrown application, cropping every .mrxs or .svs file, saving as .tif, and then uploading is not particularly feasible. Is it possible to skip white tiles without using the `--layout google` option and saving as .dzi? Thank you again!

**Comment by jcupitt** [comment]
We'd need to add a `skip-blanks` option I guess. I'll tag this as an enhancement.

I think one of the simplest ways to make dzi smaller is to just zip them. Try:

```
vips dzsave myhugeimage.svs mydzipyramid.zip
```

And `dzsave` will directly generate a zip file containing the deepzoom pyramid. These zips are much simpler to manage than huge directory trees, and perhaps half the size on disc. With a bit of javascript, you can make your viewer read directly from the zip, you don't ever need to unpack it.

**Comment by jcupitt** [comment]
I hacked up a quick patch to experiment with this. If you set `--skip-blanks` it won't output tiles which have a maximum difference from `background` of less than five.

@felixbuenemann, do you think this sounds useful?

I tried on a mrxs image:

```
$ vips dzsave Mirax2.2-1.mrxs x.zip
$ ls -l x.zip
-rw-r--r-- 1 john john 2445901070 Dec 19 14:17 x.zip
$ vips dzsave Mirax2.2-1.mrxs x.zip --skip-blanks
$ ls -l x.zip
-rw-r--r-- 1 john john 1913809531 Dec 19 14:04 x.zip
```

So a 20% saving, in this case. For many images of course you see no saving, since solid white means overexposure, usually.

**Comment by bverem** [comment]
I'll see if I can give both of those options a whirl. I'll be away from my workstation most of the time until the new year, so it may be a week or two before I can try it out. Thank you again!

**Comment by jcupitt** [comment]
Good idea, I pushed a thing to [dzsave-skip-blanks](https://github.com/libvips/libvips/tree/dzsave-skip-blanks) to make it an int-valued parameter. I left it as a pixel value rather than a percentage.

**Comment by felixbuenemann** [comment]
What exactly is a pixel value in this context?

**Comment by felixbuenemann** [comment]
It looks to me, like the code might have an off-by-one problem.

What do you specify, if you only want to skip the exact background color?

**Comment by jcupitt** [comment]
Oh hmm yes I guess. I was thinking 0 == false == do nothing. Would anyone want to skip with no fuzz at all?

I'll change it to -1 for do nothing, that seems to be the non-zero value we use elsewhere.

**Comment by felixbuenemann** [comment]
I tested with some clean product images of clothing, which where all square with various amounts of whitespace (eg. a trouser would have more than a shirt).

Test Shirt 3360x3360 PNG to DZI:

* `--skip-blanks -1`: 318 files, 2.7 MB, 0.943 s
* `--skip-blanks 0`: 170 files, 2.1 MB, 0.765 s

Test Overalls 5458x5457 JPEG to DZI:

* `--skip-blanks -1`: 663 files, 2.9 MB, 1.801 s
* `--skip-blanks 0`: 198 files, 1.1 MB, 0.971 s

Test [Earth from Suomi NPP](https://visibleearth.nasa.gov/view.php?id=78314) 12000x12000 JPG to DZI:

* `--skip-blanks -1`: 3082 files, 21 MB, 7.938 s
* `--skip-blanks 0`: 1402 files, 14 MB, 5.042 s
* `--skip-blanks 5`: 1389 files, 14 MB, 5.154 s

Test Earth from Suomi NPP 12000x12000 JPG to DZI in ZIP:

* `--skip-blanks -1`: 1 files, 15 MB, 6.088 s
* `--skip-blanks -1 --compression 1`: 1 files, 13 MB, 6.596 s
* `--skip-blanks -1 --compression 9`: 1 files, 13 MB, 6.596 s
* `--skip-blanks 0`: 1 files, 12 MB, 4.320 s
* `--skip-blanks 0 --compression 9`: 1 files, 12 MB, 4.559 s

My test images were so clean that going from `--skip-blanks 0` to `--skip-blanks 5` didn't make a significant difference.

I also tried serving the incomplete DZI images to [OpenSeadragon](https://openseadragon.github.io) and it worked without visual problems, because OpenSeadragon will just show an interpolated image from a lower level if a tile cannot be loaded. However it will spam the browser's Javascript console with an error. To avoid that you can set your webserver to serve a 1x1 px image with the correct background color or a transparent image and set the html background color via css or just patch the error out.

@jcupitt I noticed that the default for `--skip-blanks` is 5, shouldn't it be disabled by default?

Also I couldn't figure out how to run dzsave on the cli with a source PNG image with an alpha channel and specify the background color at the same time. When I specified `--background 255` it was rendered with a black background anyways.

**Comment by felixbuenemann** [comment]
Btw. you can serve the following `index.html` in the same dir as your `.dzi` files using any webserver to test the zoom images:

```html
<!DOCTYPE html>
<html>
<head>
<style type="text/css">
html, body, #openseadragon1 {
    width: 100%;
    height: 100%;
    margin: 0;
    padding: 0;
    overflow: hidden;
    /* background: red; */
}
</style>
</head>
<body>
<div id="openseadragon1"></div>
<script src="https://cdn.jsdelivr.net/npm/openseadragon@2.4/build/openseadragon/openseadragon.min.js"></script>
<script type="text/javascript">
    var viewer = OpenSeadragon({
        id: "openseadragon1",
        prefixUrl: "https://cdn.jsdelivr.net/npm/openseadragon@2.4/build/openseadragon/images/",
        tileSources: "example.dzi",
        wrapHorizontal: false,
        minZoomImageRatio: 0.0,
        maxZoomPixelRatio: 1.0
    });
</script>
</body>
</html>
```

**Comment by jcupitt** [comment]
Nice tests @felixbuenemann, it's obviously a useful feature for some cases at least.

The background param to dzsave just sets the colour of the `blank.png` file, and the colour against which the tiles should be tested. If you want to flatten to JPG with that colour, you'll also need to pass the colour down to the JPG saver.

**Comment by bverem** [comment]
Happy New Year! My tests for some of my Mirax files I had laying around (I also ran autocrop since I'm currently predominantly using Mirax files--hopefully using Aperio .svs files soon--and I wanted to see the differences):

Biopsy specimen (smaller): 
original Mirax: 141.3 MB
'--skip-blanks=-1': 408,383 items, 732.6 MB
'--skip-blanks=0': 24,231 items, 95.6 MB
autocrop: 393,339 items, 208.0 MB

Resection specimen (larger): 
original Mirax: 2.5 GB
'--skip-blanks=-1': 408,383 items, 2.3 GB
'--skip-blanks=0': 182,987 items, 1.9 GB
autocrop: 392,791 items, 2.2 GB

It seems like for larger specimens (i.e., tissue that takes up most of the image), the space savings are somewhat minimal (though better than what is used for autocrop for Mirax files), but for those with a lot of white space (such as biopsy specimens), it's substantial. It appears to work out-of-the-box with OpenSeadragon in terms of filling in the 404 tiles, and they look the same as if I had not skipped any blank tiles.

This is absolutely fantastic. Given that many of the cases in my application are biopsy (small) specimens, this should save me a ton of space (and prolong the time for which I can stretch my funding). Thank you very much! If y'all are ever in New York City, I'd be happy to get you a pint.

**Comment by jcupitt** [comment]
OK, merged to master. Thanks everyone!
