### ISSUE TITLE
resize to fill with north gravity

### ISSUE THREAD

**Issue by Menelle** [libvips/libvips#1227]
Hello,

In an attempt to switch to vips from ImageMagick, I trying to reproduce the following process on file upload:

- resize the file to fill a width and height provided
- crop the file with a cardinal gravity provided

Since no operation is executed between those two steps, one unique method that executes resize and crop would be acceptable

I’m a the point where :

- Thumbnail would do the job but it seems to only accepts Interesting options for the crop.

- Gravity exists and use compass which is cardinal orientation. However, it seems to have a different use than gravity in ImageMagick

- I can crop oriented to north by doing this :
crop((uploaded_file.width - width) / 2, 0, width, height)

- I can size up and down by mentioning explicitely : size(:both)

Can you please guide me towards the correct direction/composition to fill then north-crop?

As an example, let say a user provides a portrait 4x3 with width of 500 and heigth of 750.
My output is a square of 1000x1000
I need the original file to be enlarged to 1000x1500, then crop from the top to keep a square of 1000x1000

.size(:both)
.something_to_fill_here
.crop((uploaded_file.width - 1000) / 2, 0, 1000, 1000)

Also, do you plan to integrate Compass as thumbnail’s crop options ? That would be great and seems to be what let user switch from ImageMagick to Vips in a breeze for regular actions.

Thank you fot all the time invested in this great lib, and for all the help you can provide.

Thomas

**Comment by jcupitt** [comment]
Hello @Menelle,

Yes, libvips 8.8 (git master) has more cropping options. You can do what you want with (I think):

```
$ vipsthumbnail shark.jpg --size 1000 --smartcrop high
```

Meaning resize to 1000x1000, crop, and position the crop box at the high end of the axis that needs cropping.

With 8.7, you'd need to do it yourself: get the image dimensions, calculate a size for the longer axis that makes the shorter axis 1000 pixels, thumbnail to that, then crop to 1000 x 1000. In (eg.) Python:

```python
#!/usr/bin/python3

import sys
import pyvips

image = pyvips.Image.new_from_file(sys.argv[1])
factor = 1000 / min(image.width, image.height)
target_width = round(image.width * factor)  
target_height = round(image.height * factor)

thumb = pyvips.Image.thumbnail(sys.argv[1], target_width, height=target_height)
thumb = thumb.crop(thumb.width - 1000, thumb.height - 1000, 1000, 1000)

thumb.write_to_file(sys.argv[2])
```

**Comment by jcupitt** [comment]
Oh, are you using sharp? You'd need to ask there, they have a different system for this stuff.

**Comment by Menelle** [comment]
Hello @jcupitt 

Thank you very much for this detailled explanation.
I'm using ruby-vips with @janko image-processing gem.

My project currently lives on Heroku which do not provides vips as default libs, and buildpacks still loads older versions of the lib for now.
However, your example for 8.7 was easy to translate in rails so I guess that's the path I'm taking for now.

Thank you again for the work and the good support

**Comment by janko** [comment]
Thanks @jcupitt. I tried it out with ruby-vips:

```rb
require "vips"
require "open-uri"
require "tempfile"

source = open("https://images.unsplash.com/photo-1548761208-b7896a6ff225?ixlib=rb-1.2.1&q=85&fm=jpg&crop=entropy&cs=srgb&dl=andy-holmes-1331088-unsplash.jpg")

image = Vips::Image.new_from_file(source.path)

factor        = Rational(1000, [image.width, image.height].min)
target_width  = (image.width * factor).ceil # ceil instead of round to avoid white 1px line on smaller side edge
target_height = (image.height * factor).ceil

thumb = image.thumbnail_image(target_width, height: target_height)
thumb = thumb.crop(thumb.width - 1000, thumb.height - 1000, 1000, 1000)

result = Tempfile.new(["result", ".jpg"])

thumb.write_to_file(result.path)

system "open", "-W", result.path
```

but it seems that this script does the opposite cropping, I get the bottom part of the image as the result instead of the top (which I think was the one requested by OP):

<img src="https://user-images.githubusercontent.com/795488/52540308-6718ee00-2d88-11e9-8ea0-34dec5966698.jpg" width=400/>

**Comment by jcupitt** [comment]
Oh, sorry, I misunderstood, I thought the OP wanted the north bit cut off.

Just change it to:

```ruby
thumb = thumb.crop(0, 0, 1000, 1000)
```

Or set `crop` to `:low`.

**Comment by janko** [comment]
Thank you. Now that I re-read the OP's question, I think *I* was the one that misunderstood. But now I have a better understanding on how the algorithm works, so thanks for that 😃

**Comment by jcupitt** [comment]
Oh heh, well as long as it works! 

I'd avoid `thumbnail_image`, if possible. It can't do any of the shrink-on-load tricks, so it's much, much slower. I'm sure you know.

`thumbnail` and `thumbnail_buffer` are both a lot quicker.

**Comment by jcupitt** [comment]
... I should have said, if you are working uri -> uri, or perhaps on S3 buckets, it's best to read to a memory buffer, `thumbnail_buffer` from that, `write_to_buffer` to an output string, and then post that off. Again, I'm sure you know etc.

**Comment by janko** [comment]
> I'd avoid `thumbnail_image`, if possible. It can't do any of the shrink-on-load tricks, so it's much, much slower.

I didn't know there was a big difference between `thumbnail` and `thumbnail_image`. The ImageProcessing gem is designed in a way that "thumbnailing" is just one in the sequence of processing steps. So, when `thumbnail_image` was released, I was happy that the design could now be much simpler, as I didn't have to use `.thumbnail` when loading the image.

Man, you're absolutely right, resizing the lion image above to 400x400 takes 0.4s with `thumbnail_image`, but only 0.1s with `thumbnail`. I'll need to rewrite ImageProcessing to apply thumbnailing *first* (with `.thumbnail`), then the rest of the operations. I don't know if that will cause any backwards compatibility, but I'll probably bump the major version.

> if you are working uri -> uri, or perhaps on S3 buckets, it's best to read to a memory buffer, `thumbnail_buffer` from that, `write_to_buffer` to an output string, and then post that off.

In Shrine, the "processing on upload" feature does in most cases upload storage service -> storage service, but that storage can be anything (s3, disk, Postgres blob storage), so I chose to process everything on disk. The new "on-the-fly processing" feature does storage service -> HTTP response or storage service -> storage service, but for similar reasons I found it much better to do the processing on disk. In my benchmarks I haven't seen including disk to be any slower compared to processing, but it obviously does use more I/O.

Man, your "by the way" tips are really golden, thanks a bunch!

**Comment by jcupitt** [comment]
It's not just speed -- try an SVG or PDF with `thumbnail` vs. `thumbnail_image`. 

With `thumbnail_image`, it'll render to a bitmap at the default 72 DPI, then downsize (or even upsize!) to whatever size you need. With `thumbnail`, it can render directly to the DPI you need for the output. It'll not just be faster, it'll have the correct aliasing and can look a lot better.

I see:

```
$ time vips thumbnail nipguide.pdf[page=10] x.png 200

real	0m0.064s
user	0m0.051s
sys	0m0.019s
$ time vips thumbnail_image nipguide.pdf[page=10] x2.png 200

real	0m0.101s
user	0m0.117s
sys	0m0.012s
```

Producing:

![y](https://user-images.githubusercontent.com/580843/52560888-a9c2e080-2df1-11e9-8357-49d6ab8370b4.png)

(`thumbnail_image` on the right looking a bit soft and taking 2x as long to generate)

Yes, sounds like you'd need to chop your pipeline around, what a pain. I suppose the tricky bit would be if users specify crops or other transforms in terms of original image (rather than output image) coordinates. You'd have to map them forwards through the `thumbnail` transform somehow.

You'd know much more about disc vs. memory than me, but my understanding is that most cloud services have very little `/tmp` available (perhaps only 500mb), but will have many gb of RAM. libvips is relatively light on memory, so avoiding disc means you can process more and larger images at once. I know sharp installs (for example) can have several 100 resize operations in flight at once, and at that point you do need to avoid disc if you can.

It depends on the filesystem and hardware too, but you can get IO contention if there's a physical drive behind the scenes somewhere, especially if it's shared between several machines or is getting full. 

Off topic, but what do you do about GCs? Does shrine have a strategy for this? You probably saw the magic GC code in ruby-vips:

https://github.com/libvips/ruby-vips/blob/master/lib/vips/image.rb#L149

Perhaps the generational GC is fast enough now that that doesn't matter.

**Comment by janko** [comment]
> I suppose the tricky bit would be if users specify crops or other transforms in terms of original image (rather than output image) coordinates. You'd have to map them forwards through the `thumbnail` transform somehow.

Yeah, for that reason I think it will need a major version bump, or a special API. I would like to just be able to use `thumbnail` if resizing was specified as the first step, but I don't want users to accidentally be using the slower and less accurate version. I will need to think this through, but it will be great to give ImageProcessing users such a significant performance boost.

> You'd know much more about disc vs. memory than me, but my understanding is that most cloud services have very little `/tmp` available (perhaps only 500mb), but will have many gb of RAM. libvips is relatively light on memory, so avoiding disc means you can process more and larger images at once. I know sharp installs (for example) can have several 100 resize operations in flight at once, and at that point you do need to avoid disc if you can.

Thanks for the info, I added it to my TODO list to offer that option.

> Off topic, but what do you do about GCs? Does shrine have a strategy for this? You probably saw the magic GC code in ruby-vips:

I'm afraid I didn't have much experience with Ruby's GC, and don't really know how it works. I haven't yet used libvips or ImageProcessing or Shrine in production (because of [how automation works](https://xkcd.com/1319/) 😛), so I don't know if I would have any problems with resources. That patch looks fairly ok to me.
