### ISSUE TITLE
Compiling on CentOS 6: libgsf 1.14.26 required, but only 1.14.15 is available...

### ISSUE THREAD

**Issue by r03ert0** [libvips/libvips#1228]
Hello,

I'm trying to compile libvips on CentOS 6 for using the `dzsave` function.
However, for `dzsave` to compile `libgsf 1.14.26` is required, but only `libgsf 1.14.15` is available through `https://centos.pkgs.org`. I tried to compile `libgsf` myself, but I can't figure out how to make it work... Is there a way of making `libvips` compile with the older version of `libgsf`?

Thank you!

**Comment by jcupitt** [comment]
Sorry, the centos6 packages are just very old now. You'll need to build your own libgsf. I'll make you a dockerfile.

**Comment by jcupitt** [comment]
This seems to work:

https://github.com/jcupitt/docker-builds/tree/master/ruby-vips-centos6

It builds Ruby too, but you can just cut that bit off. 

I built libgsf-1.14.27 since the current libgsf won't build on centos6 without a loot of work. Unfortunately that means there's no zip64 support, so you can't make zips bigger than 4gb.

If you can update to centos7, it's much simpler.

**Comment by jcupitt** [comment]
I'll close. Please reopen if this is still a problem.
