### ISSUE TITLE
i got this Error help!!!

### ISSUE THREAD

**Issue by airqb** [libvips/libvips#1267]
libtool: link: gcc -g -O2 -o .libs/introspect introspect.o -DG_DISABLE_ASSERT -DG_DISABLE_CHECKS -pthread -fopenmp -I/usr/lib64/glib-2.0/include -I/usr/include/libpng12 -I/usr/include/glib-2.0 -I/usr/include/ImageMagick -Wl,--export-dynamic -pthread  -lgirepository-1.0 ./.libs/libvips.so -lz -lMagickCore -lpng12 -ltiff -ljpeg -lgmodule-2.0 -lgobject-2.0 -lglib-2.0 /usr/lib64/libexpat.so -llcms2 -lgif -lwebp -lexif -lm -fopenmp -pthread -Wl,-rpath -Wl,/usr/local/lib
gcc: error: libgomp.spec: No such file or directory
make[3]: *** [introspect] Error 1
make[3]: Leaving directory `/home/ec2-user/vips-8.7.4/libvips'
make[2]: *** [all-recursive] Error 1
make[2]: Leaving directory `/home/ec2-user/vips-8.7.4/libvips'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/home/ec2-user/vips-8.7.4'
make: *** [all] Error 2

**Comment by jcupitt** [comment]
Hi, `libgomp` errors are usually problems in the imagemagick pkgconfig file. I would try without imagemagick.

**Comment by metaskills** [comment]
Hey y'all. I'm working an issue in the ruby-vips-lambda project (https://github.com/customink/ruby-vips-lambda) in response to today's (https://aws.amazon.com/blogs/compute/upcoming-updates-to-the-aws-lambda-execution-environment/) AWS environment upgrade announcements. 

In our project we build from git source and also git the `gcc: error: libgomp.spec: No such file or directory` error. I'd like to test `--without-imagemagick` but am not sure where to put this? I tried adding it to `autogen.sh` args but so far no luck. Any pointers?

**Comment by metaskills** [comment]
Ah... I think the correct flag is `--without-magick` and adding that to `autopen.sh` does appear to work past the `libgomp.spec` as far as I can tell now.

**Comment by replicat0r** [comment]
Im running into the same issue, im just trying to compile vips on amazon linux ami for elasticbeanstalk. I don't know anything about c++, so i am just comping and pasting commands. 


Here is the command i am following
`VIPS_VERSION=8.7.4
 VIPS_URL=https://github.com/libvips/libvips/releases/download

RUN cd /usr/local/src \
	&& wget $VIPS_URL/v$VIPS_VERSION/vips-$VIPS_VERSION.tar.gz \
	&& tar xzf vips-$VIPS_VERSION.tar.gz \
	&& cd vips-$VIPS_VERSION \
	&& ./configure \
	&& make \
	&& make install
`

Where do I pass in --without-magick? in the autopen.sh file?

**Comment by jcupitt** [comment]
Give the option to `configure`:

```
./configure  --without-magick
```

And check the output carefully. There's a summary printed at the end listing all the features that have been detected.

**Comment by jcupitt** [comment]
It's best not to run `autogen.sh` unless you really have to. Use the included `configure` script if you can.

**Comment by replicat0r** [comment]
> Give the option to `configure`:
> 
> ```
> ./configure --without-magick
> ```
> 
> And check the output carefully. There's a summary printed at the end listing all the features that have been detected.

ahh great. Let me try that when I get home tonight! Thanks for the quick response!! 

Btw, your install script for 2018.03 linux ami was really help, it was linked in another issue, but since then deleted, so i had to go back to the state of your repo in march 2019 this year to find it, I am using this script to install Vips on elasticbeanstalk AMI. 

Perhaps you can consider adding it back to your docker install repo?

I ended up installing gcc64 and symlinking it, that seem to got around this libgomp.spec error, the issue is that this "hack" fix involves symlinking 3 very specific files on the host system. which will break is the installation location is changed..
I have no idea what I am doing around compilation and building stuff, I am mostly a webguy, I need vips for an imagining processing library I am using for rails. 

Passing in ./configure --without-magick seem to be a more reliable way of compiling this, is there any other side effects to using vips without imagemagick?

here is the install script I ended up using to install VIPS based on your docker file

`files:
  "/home/ec2-user/post_deployment/install_vips.sh" :
    mode: "000775"
    owner: root
    group: users
    content: |
      #!/usr/bin/env bash

      sudo yum update -y \
      && sudo yum groupinstall -y "Development Tools" \
      && sudo yum install -y wget tar

      sudo yum install -y \
      libpng-devel \
      glib2-devel \
      libjpeg-devel \
      expat-devel \
      zlib-devel 

      sudo yum install -y gcc64

      VIPS_VERSION=8.8.0
      VIPS_URL=https://github.com/libvips/libvips/releases/download
      
      sudo ln -s /usr/lib/gcc/x86_64-amazon-linux/6.4.1/libgomp.spec /usr/lib64/libgomp.spec
      sudo ln -s /usr/lib/gcc/x86_64-amazon-linux/6.4.1/libgomp.a /usr/lib64/libgomp.a
      sudo ln -s /usr/lib64/libgomp.so.1.0.0 /usr/lib64/libgomp.so

      wget ${VIPS_URL}/v${VIPS_VERSION}/vips-${VIPS_VERSION}.tar.gz \
      && tar xzf vips-${VIPS_VERSION}.tar.gz \
      && cd vips-${VIPS_VERSION} \
      && ./configure \
      && sudo make \
      && sudo make install

container_commands:
  01_run_script:
    command: "/home/ec2-user/post_deployment/install_vips.sh"
`

Let me know what you think!

Thanks for everything
