### ISSUE TITLE
Pdfium is not thread safe

### ISSUE THREAD

**Issue by duedal** [libvips/libvips#1275]
How do you get around the lack of thread safety in Pdfium, combined with the [general promise that libvips is thread safe](https://libvips.github.io/libvips/API/current/using-threads.html)?

Pdfium's mailing lists are quite clear that they are not thread safe;
https://groups.google.com/forum/#!msg/pdfium/kyIdh_J4csg/K1LvfPiHDwAJ
https://groups.google.com/forum/#!topic/pdfium/HeZSsM_KEUk

**Comment by jcupitt** [comment]
Hello, libvips puts a lock around PDFium calls so it'll never try to process the same document with more than one thread. This seems to work, in the limited testing I've done.

From your links it looks like we might need to prevent parallel access to different docs as well.

Unfortunately the PDFium build system has changed enough since we added PDFium load to break everything :( It'll need a few days work to get it functioning again.

**Comment by duedal** [comment]
Thank you very much for the swift reply, I was looking for a mutex lock or something but didn't find it (I guess I was looking in the wrong place).

We're calling PDFium from Go, and I wondered if it was possible to reduce lock contention without going to multi process.
Currently using this third-party binary distribution of PDFium; https://github.com/bblanchon/pdfium-binaries

**Comment by jcupitt** [comment]
The lock is in the `vips_linecache()` call in `vips_foreign_load_pdf_load()`. It ensures calls into `vips_foreign_load_pdf_generate()` are single-threaded.

That binary PDFium distribution looks interesting. The last time I looked at PDFium itself, they'd broken library builds completely -- I guess they were concentrating on building as a component of chrome. Hopefully that's fixed now.
