### ISSUE TITLE
Size of windows

### ISSUE THREAD

**Issue by Gal-Schwietzer** [libvips/libvips#1321]
I was reading the documentation about opening files and saw that small files (under 100mb) are loaded entirely into memory and larger files are read using a series of windows. I was wondering how the size of those windows is chosen? Is it a fixed size or dependant on the size of the image? 
Any information is welcomed.

**Comment by jcupitt** [comment]
Hello Gal, you can see the logic here:

https://github.com/libvips/libvips/blob/master/libvips/iofuncs/window.c#L399

When an operation requests a region of an image, it searches for an existing window which can supply those pixels. If there is none, a new window is created (or an old window recycled) which encloses those pixels, plus a number of scanlines above and below.

This extra margin is supposed to give the system a degree of "slack" and prevent continual remapping.

So:

- it operates in terms of scanlines rather than bytes, so window size varies with image width
- windows are shared and reused between threads with a refcount system to control access
- windows have margins above and below to reduce continual reallocation
- the libvips threading system tries to keep threads together to improve locality, though of course this is not always possible (eg. consider a 90 degree rotate)

What could still be done:

- more tuning on typical workloads
- improve performance on Windows (the equivalent to mmap has rather different time/memory behaviour)

Cases to consider:

- simple pixel arithmetic (1:1 mapping between input and output)
- area operations, like convolution (there's a margin to consider)
- 90 degree rotate (the terrifying pathological case for streaming libraries)
- things like FFT (each output pixel depends on every input pixel)

There's an analogous system to manage pixel buffers in `buffer.c`.

**Comment by Gal-Schwietzer** [comment]
Thank you for the quick response! 
does an operations like vips_getpoint requests a window as well? and if so is it just the minimum size?

**Comment by jcupitt** [comment]
Yes, getpoint will request a 1x1 area. It is very slow! You're not supposed to use getpoint for any serious processing, it's just convenient occasionally.

If it's from a mmaped file, `window.c` will then size that up.
