### ISSUE TITLE
Better PNG compression

### ISSUE THREAD

**Issue by andrews05** [libvips/libvips#1322]
Vips's mozjpeg support is really great for optimizing jpegs for web usage. I was thinking it would be nice if vips could optimize PNGs as well. My current favorite tool is [ECT](https://github.com/fhanau/Efficient-Compression-Tool) which, along with smart palette reductions, uses a highly optimized version of zopfli to achieve excellent deflate compression with surprising performance.
Any chance something like this could be added to vips?

**Comment by jcupitt** [comment]
Hello, libvips will compute optimised 8-bit palette PNGs and you can alter the deflate settings, but that's it. Dedicated PNG optimisation tools do quite a bit more work.

ECT seems to use optipng for PNG optimisation:

http://optipng.sourceforge.net/

It might be possible to use that for PNG output. Someone would need to study the API.

**Comment by felixbuenemann** [comment]
Btw. if you want to speed up PNG compression, it's possible to link libpng against https://github.com/cloudflare/zlib, though the PNG build system is a bit borken and prefers system zlib if found.

I'm using https://nixos.org/patchelf.html to fix the rpath in my lambda builds:

```
patchelf --set-rpath /var/task/lib /var/task/lib/libpng16.so.16.38.0
```

This does not optimize the size of 24 bit png in a way which zopflipng or [pingo](https://css-ig.net/pingo) can do, but it allows you to increase the zlib compression level without loosing too much performance.

I think zopflipng makes a huge tradeof in processing time to gain better compression, so I think it makes more sense to run it as a standalone tool. Just write your png with `compression=0,filter=none` and pass the unoptimized png to `zopflipng`.

If you are looking fpr png8+alpha, you should build libvips against [libimagequant](https://github.com/ImageOptim/libimagequant) using `palette,compression=0,filter=none` and pass the resulting file to zopflipng for optimized compression.

While zopflipng can reduce to 8-bit palette by itself, it does not have the advanced perceptual quantization from libimagequant, which is also used by pngquant.

My experience is that zopfli compression is prohibitively slow to process images in large quantities or near real time.

When comparing compression, cloudflare's zlib fork is about 3-4 times faster than madler's zlib, while zopli with a single iteration is about 35-40x slower than cloudflare zlib at level 9.

Looking at the filesize, zopfli will give you maybe 10% gain over zlib level 6 or 6% over zlib level 9.

The optimized zopfli compressor in ECT is somewhat impressive, since at level 3 it can produce pngs similar in size to vanilla zopli with default iterations at only about 4-5x the time as cloudflare's zlib.

The problem is that as far as I know you can't simply replace the compression implementation in libpng and would have to either compress in a two-pass process (write uncompressed png, recompress) or completely replace the png writer with something like lodepng.

Overall that seems like a lot of work, if you keep in mind that many clients on the web today can use WebP compression, including lossless and near-lossless modes that are supported by libvips.

**Comment by andrews05** [comment]
Would it be possible to integrate with a rust library such as [oxipng](https://github.com/shssoichiro/oxipng), if it had the appropriate APIs?

**Comment by DavidVaness** [comment]
echoing the request made by andrew05, would be nice to add oxi

**Comment by andrews05** [comment]
Oxipng does now have a "raw" API that might be suitable for use here. If there's anything further that would be helpful to enable integration, just let me know.
