### ISSUE TITLE
support 1, 2 and 4 bits per pixel PNG output

### ISSUE THREAD

**Issue by fzzylogic** [libvips/libvips#1388]
Found VIPS after running into a problem showing high resolution 1 bit diagrams in a web browser. It's fantastic. I'm using the 64 bit pre-built Windows binary (8.8.1) from github releases page. Also intend using pyvips, but using the command line for now.

The input images used are TIF with CCITT G4 compression. There are a few hundred thousand of them, so to conserve disk space, it would be great to save the output as 1 bit as well.

So I'm trying to find if it's possible to set dzsave output down to 1 bit colour. I tried setting colours to 2, but the output is still 256 colours:

`vips.exe dzsave diagram.tif diagram --tile-size 2048 --overlap 1 --suffix .png[colours=2]`

Is there a simple way to use either the command line or pyvips to generate DeepZoom output at 1 bit in a single operation (without saving to disk and then reading again to down-sample)? 

Would really appreciate any pointers on this one, thanks!

**Comment by jcupitt** [comment]
Hello @fzzylogic,

libvips does not support one-bit PNG output. You'll only get that with TIFF tiles, which I don't think DeepZoom supports.

You could try using iipimage instead of deepzoom. That can serve from TIFF pyramids rather than directory trees:

https://iipimage.sourceforge.io/

It requires a server-side add-on and is quite complex to set up, plus of course you'd need to change viewer.

Actually, I had no idea that PNG supported 1, 2, and 4 bit images until I checked the standard just now. I don't think (?) I've ever seen one. Let's leave this issue open as an enhancement in case anyone feels like adding this:

https://en.wikipedia.org/wiki/Portable_Network_Graphics#Pixel_format

**Comment by jcupitt** [comment]
Note: we support 1/2/4 bit PNG input since we set the `_expand()` option in libpng decode.

This issue would involve adding some option to PNG save meaning "only save this many bits".

**Comment by angelmixu** [comment]
My company would be happy if libvips supported 1,2, and 4 bits for loading and saving in tiff too :)

**Comment by jcupitt** [comment]
Hi @angelmixu, you can load 1/2/4 bit TIFFs, and save 1 bit TIFFs. 

You're right that 2 and 4 bit TIFF save is not supported :(

**Comment by jcupitt** [comment]
8.10 now supports 1/2/4 bit tiff load and save.

PNG is not yet done.

**Comment by fzzylogic** [comment]
@jcupitt Thanks for your work on this John!

**Comment by jcupitt** [comment]
1, 2, 4 bit PNG write is in now. This will be in libvips 8.10:

https://github.com/libvips/libvips/commit/4bf27acccbf3e660522feade3ad5aebcb4a61075

Example:

```
vips copy k2.jpg x.png[bitdepth=1]
```

**Comment by fzzylogic** [comment]
@jcupitt Fantastic, thank you very much John!
