### ISSUE TITLE
vips_cache_remove() is called by signal without mutex lock

### ISSUE THREAD

**Issue by MaxKellermann** [libvips/libvips#1484]
Every access to `vips_cache_table` must be protected by having the mutex `vips_cache_lock` locked. However, here a signal gets connected:
https://github.com/libvips/libvips/blob/1a2a4a41f1cc2c64f3fd24cee0b105e062028bfd/libvips/iofuncs/cache.c#L631-L632
This signal will be emitted without locking `vips_cache_lock` here:
https://github.com/libvips/libvips/blob/1a2a4a41f1cc2c64f3fd24cee0b105e062028bfd/libvips/iofuncs/operation.c#L629
Thus `vips_cache_remove()` gets called without the lock, however it also doesn't acquire the lock, but accesses `vips_cache_table`:
https://github.com/libvips/libvips/blob/1a2a4a41f1cc2c64f3fd24cee0b105e062028bfd/libvips/iofuncs/cache.c#L546-L550
This will eventually crash.
Note that adding the lock to `vips_cache_remove()` will still crash, because that will just wait until another thread releases the lock, and meanwhile the other thread may have destroyed the object.
(From GLib API documentation, it is not clear whether the whole `g_signal` library is thread-safe at all. And even if so, what happens if you disconnect a signal that is currently already running? Will it wait for completion? If yes, then you have just produced a deadlock, because `g_signal_handler_disconnect()` is called while holding the lock.)

**Comment by jcupitt** [comment]
Hi Max,

Yes, you're right, this should be improved.

How about making invalidate advisory rather than immediate? Operations could set a mark on cache entries meaning "this entry is no longer valid", then the entry would be removed next time that operation is looked up.

This breaks the loop (now the cache can remove operations, but operations can't remove cache entries), so it should be safer (I think). Everything is inside a mutex, at least.

I put your name on the change, I hope that's OK.

**Comment by jcupitt** [comment]
More generally, you're also right about signals and threading, it's a murky area. 

Emit holds a ref to the object that's emitting during the process, and ref/unref is threadsafe, but that often won't be enough. Doing more than the minimum in a signal handler is asking for trouble.

**Comment by jcupitt** [comment]
I think this is at least partly addressed now in gut master. Please open a new issue if there is still a problem.
