### ISSUE TITLE
check webp save speed

### ISSUE THREAD

**Issue by jcupitt** [libvips/libvips#1495]
`cwebp` should be the same speed as vips `webpsave` (they both just make calls into libwebp), but vips seems to be slower:

```
$ time cwebp -m 0 -q 75 ~/pics/k2.jpg -o x.webp
real    0m0.102s
user    0m0.087s
sys 0m0.012s

$ time vips copy ~/pics/k2.jpg x.webp[Q=75,reduction-effort=0,strip]
real    0m0.144s
user    0m0.129s
sys 0m0.024s
```

You see a bigger difference for larger images, so it's not just startup cost.

There must be some new webp save feature that `cwebp` is using -- someone needs to read `cwebp.c` and see what they are doing.

**Comment by kleisauke** [comment]
I noticed that cwebp incrementally writes to a file instead of using the `WebPMemoryWriter` when `-metadata none` is used (which is by default):
https://github.com/webmproject/libwebp/blob/be738c6d396fa5a272c1b209be4379a7532debfe/examples/cwebp.c#L984-L990

I had a quick attempt to implement this in vips: https://gist.github.com/kleisauke/28312f233bc0d195585d327a28e9f9ba

But didn't see a big difference. I used [this image](https://upload.wikimedia.org/wikipedia/commons/8/8b/Picture_of_K2.jpg) for benchmarking.
