### ISSUE TITLE
local adaptive threshold for binarization

### ISSUE THREAD

**Issue by killdash9** [libvips/libvips#1516]
any plans to support something like imagemagick's -lat parameter?

**Comment by jcupitt** [comment]
Hello @killdash9,

It's probably not worth implementing as a separate operator, since it's pretty easy to make yourself.

http://www.imagemagick.org/script/command-line-options.php?#lat

Eg. In Python:

```python
def lat(image, sigma, offset):
    return image > image.gaussblur(sigma) + offset
```

That'll actually be better than the IM one since it will use a circular mask. It should be faster too.

**Comment by killdash9** [comment]
@jcupitt -- I am really new to libvips and I don't really understand what gaussblur does (even after reading its api documentation).  But from the name, I'm not sure it would do the same thing as a lat.  ImageMagic's LAT turns pixels either black or white based on whether the pixel's grayscale value is above or below a threshold determined from the mean local pixel value plus some multiple of the stddev.  Can you confirm that this is what your python snippet does, or describe how it is different?

**Comment by jcupitt** [comment]
Hello again,

The imagemagick docs just say:

<blockquote>
Adaptively threshold each pixel based on the value of pixels in a surrounding window. If the current pixel is lighter than this average plus the optional offset, then it is made white, otherwise it is made black.
</blockquote>

Which is what that line of Python is doing --- gaussblur is finding the local average, then image > gaussblur + offset is TRUE (white) if a pixel is greater than the local average by offset.

**Comment by killdash9** [comment]
Thank you for the quick response.  I think I am confused by the operator overloading, applying a greater than operation to an entire image object instead of an individual pixel.  Perhaps that is just a libvips pattern that I need to understand.

**Comment by jcupitt** [comment]
`greater_than` is just:

```python
def greater_than(image_a, image_b):
  for (x, y) in image_a.coordinates:
    if image_a(x, y) > image_b(x, y):
      result(x, y) = 255
    else:
      result(x, y) = 0
```

Likewise, `add` adds pairs of pixels, `gaussblur` sets the output to the local average, and so on.

libvips has a full set of the basic operations and a full set of overloads, plus an efficient way to compose operations together. You can mostly just type formula and they will be executed quickly and without needing much memory.

**Comment by CanadianHusky** [comment]
Excellent question and excellent answers. I am working on the exact same issue and I am blown away by the speed difference and low memory use of netvips and would love to see all the above functions implemented in the .Net binding Netvips. I have posted questions on the Netvips forum at https://github.com/kleisauke/net-vips/issues/ asking for translations of your python snippets to C# because python code is extremely short and powerful. I could not figure out how to implement that in C#

Also I agree with @killdash9  comments, the -lat parameter in IM has widthxheight-offset parameters. I do not see the size parameter in the python implementation (circular or square or rectangle would not matter, as long as there is a size option)

def lat(image, sigma, offset):
    return image > image.gaussblur(sigma) + offset

using the widthxheigth (I use mostly square area) I can control how large of an area is treated as a block for thresholding and it makes a huge impact on the result. I do not see that parameter in the python implementation, only the offset value and the sigma value of the gaus blurr exist, or am I missing something?

For preserving fine detail or removing large noisy area playing with the square size (or circle radius) is extremely important. 
thank you

**Comment by CanadianHusky** [comment]
there is another major concern with implementing the 'greater_than' function with external code instead of the libvips library itself

I have not tested the pythong implementation but the C# implementation is guaranteed to fail on large images or will run extremely slow.
As far as I can see there is a double loop over the whole image comparing all pixels of the original images against the gaussian blurred version to determine the threshold result.
Running that loop in C# is not possible  because of .Net memory limit  https://stackoverflow.com/questions/29175585/what-is-the-maximum-resolution-of-c-sharp-net-bitmap

meanwhile libvips is able to handle images with 30,000x60,000 pixels just fine because of your brilliant design, instead of loading the whole bitmap into memory. I work in the 10,000x20,000 pixel range mostly but sometimes larger images happen.

all the benefits of libvips would be lost if trying to implement thresholding based on such a pixel comparison loop, even for 'normal' smaller images

**Comment by jcupitt** [comment]
Sorry, I wasn't clear, that python code for `greater_than` was just to try to show how the operation works. The real code is here:

https://github.com/libvips/libvips/blob/master/libvips/arithmetic/relational.c#L139

So it's in C and it's part of libvips. You should be able to write that definition of `lat` in C# in one line too. NetVips has all the same operator overloads.

You set the size of the `lat` window with `sigma` -- it sets the sigma of the gaussian. It's very roughly the radius of the blob in pixels, so 2 means (about) a 4x4 window. The edges are soft and the mask is circular, so it's not an exact translation.

**Comment by jcupitt** [comment]
You can see the matrix it uses for each value of sigma with:

```
$ vips gaussmat x.csv 2 0.2
$ more x.csv
2	4	6	6	6	4	2
4	7	11	12	11	7	4
6	11	16	18	16	11	6
6	12	18	20	18	12	6
6	11	16	18	16	11	6
4	7	11	12	11	7	4
2	4	6	6	6	4	2
```

So sigma 2 is actually 7x7 pixels, though it falls off quickly at the edges.

**Comment by CanadianHusky** [comment]
You are right. there is no need for external looping. I misunderstood the post.
Here is the working C# code and it works frighteningly last compared to IM or anything else. 
Parameters need to be tuned based on input image.

{
    string input = @"c:\temp\input.jpg";
    double sigma = 10;
    double minAmpl = 0.5;
    int offset = -10;
    Image vipsimg = Image.NewFromFile(input, true, access: Enums.Access.Sequential);
    Image blurred = vipsimg.Gaussblur(sigma, minAmpl, precision: Enums.Precision.Integer) + offset;
    Image result = vipsimg > blurred;
    result.WriteToFile(@"C:\temp\output.jpg");
}

**Comment by jcupitt** [comment]
Glad it works! Int is the default, so you could write:

```C#
    Image result = vipsimg > vipsimg.Gaussblur(sigma) + offset;
```

**Comment by CanadianHusky** [comment]
I think this question is a one liner too, but I could not find it. Sorry.

How to I turn a pixel completely black and make the image bitonal ? 

This image is the result of an output area
![image](https://user-images.githubusercontent.com/35332003/76605650-dcbe3300-6521-11ea-9c82-b2442906e388.png)

I tried the `.ifthenelse` function, but I must be doing something wrong 
The output should be an image with 2 colors (bitonal) and have black or white pixels only, same as @killdash9  asked originally in his post

If the pixel intensity of output.jpg is over 10% (parameter) the final image should have black pixel, otherwise white.

thank you

**Comment by CanadianHusky** [comment]
I tried this

```
Dim color_tuple = {25, 25, 25}
Dim threshold As Image = (result > color_tuple).Ifthenelse(255, 0)

```
but the result of threshold still has all color pixels

**Comment by jcupitt** [comment]
Make the image monochrome, not rgb.

```
# pixels less than 20 become 255, others are 0
y = x.colourspace("b-w") < 20
```

**Comment by jcupitt** [comment]
Or you can just test the green channel, which is usually the most important one.

```
y = x[1] < 20
```

**Comment by jcupitt** [comment]
I think I said before, but nip2 is a really useful tool for developing libvips image processing pipelines:

https://github.com/libvips/nip2

There's a win binary here:

https://github.com/libvips/nip2/releases/tag/v8.7.0

You can write a set of formula (or click menu items) and see all the intermediate images, like a spreadsheet. As you edit formula, all the images update. At the end, it should be easy to turn the workspace into a C# program.

**Comment by CanadianHusky** [comment]
Yes, I installed nips2 for testing. It is indeed excellent for tuning parameters and experimenting with filters. 
But for 'normal' programmers thinking of an arithmetic operation like 
`y = x.colourspace("b-w") < 20`
is initially difficult because it is not the 'normal' math we are used to. The concept of treating a whole image as a single variable feels 'weird' at first.
libvips requires a different kind of thinking to get used to, and the benefits are enourmous.
the suggested monochrome function works perfectly now. 
thank you very much

**Comment by jcupitt** [comment]
Try `y = x[1] < 20` as well, it should be just as good, and a bit quicker.

**Comment by CanadianHusky** [comment]
for my sample file, after 5 runs, averaged
2800 ms -----  y = x.colourspace("b-w") < 20
2500 ms ------ y = x[1] < 20

however the result is not identical and something is weird

original
![image](https://user-images.githubusercontent.com/35332003/76610567-26128080-652a-11ea-98e4-174754ace4c2.png)


thresholding result, left :  Y=x[1]<20,  right : y = x.colourspace("b-w") < 20
![image](https://user-images.githubusercontent.com/35332003/76610466-024f3a80-652a-11ea-8445-35027924b5e3.png)

I want to preserve as many as possible pixels

**Comment by jcupitt** [comment]
I forgot you had coloured line art. Yes, stick to `colorspace`.

**Comment by CanadianHusky** [comment]
the intensity filter of 20 works in reverse

this is the desired result and is achieved with 
y = x.colourspace("b-w") < 235  '(255-20)

![image](https://user-images.githubusercontent.com/35332003/76611454-966dd180-652b-11ea-97bf-a7602f4544d2.png)

thank you for all the help
