### ISSUE TITLE
Modify big tiffs

### ISSUE THREAD

**Issue by MathemanFlo** [libvips/libvips#1610]
Hello,
I have yet another wuestion concerning something different. I would like to modify big 1bit TIFF images by inpainting lots of small rectangles at various places in the image.
What I did is: Load the image in memory to avoid a temporary file and to speed up everything.
`VImage yellow = VImage::new_from_file(yellowTIFF.c_str(), VImage::option()->set("memory", true)->set("access", VIPS_ACCESS_RANDOM));`
It uses 16GB of RAM which is completely fine.
In the next step I want to modify it using regions because the pipeline might not be the best tool for 1000s of rectangles.
Thus I activate inplace modifications by 
`vips_image_inplace(yellow.get_image());`
Then I use 
```
VipsRegion* reg = vips_region_new(yellow.get_image());
/* .. */
vips_region_prepare(reg, &r);
/*..*/
vips_region_paint(reg, &r, 0);
/* OR */
*VIPS_REGION_ADDR(reg, x, y) = 0
g_object_unref(reg);
```
To paint rectangles or more complicated patterns.
This works excellent and is also quite fast. I can even do this in parallel because the regions do not overlap.
But the problem is, as soon when I call `vips_image_inplace(yellow.get_image());` the image gets copied and my program uses 32GB of memory which is undesired.
I read a bit in the source code of libvips and found out that this has to do with `VIPS_IMAGE_PARTIAL` in `vips_image_wio_input` which is called by `vips_image_inplace`. There I can see 
```
/* Change to VIPS_IMAGE_SETBUF. First, make a memory 
		 * buffer and copy into that.
		 */
		t1 = vips_image_new_memory();
		if( vips_image_write( image, t1 ) ) {
			g_object_unref( t1 );
			return( -1 );
		}
```

Is there a nice possibility to avoid this? Or is there even a better way to do my modifications? Unfortunately it was not so easy for me to find out how to use regions because I couldn't find any example so I might do it the wrong way. For my use case I could ensure that the positions of the rectangles are sorted acending in y coordinate so a sequential approach would also work out as long as I can ensure that no temporary file is created.
By the way image_inplace seems to be missing in the C++ wrapper. If you are interested in I could add some of those missing functions.
Thank you very much for your help.
Florian

**Comment by jcupitt** [comment]
Hello again,

I had a look and you're being bitten by libvips lazy loading of random access images from sources which do not support random access.

When you open a file (eg. `y = Image.new_from_file(x)`, it just fetches the header and decode is delayed until the first pixel access. Behind the scenes, the load returns something like the result of a copy operation.

When the code for the copy first executes, it decodes the image to a temp area (it'll be a temp disc file for large images, a memory area for small images) and then forwards pixels from there. This means that the image you get back from load isn't the actual image, it's a proxy. So when you call `vips_image_inplace()`, it's forced to make a copy of the memory area rather than just returning it.

The fix is to take control of the open process yourself. I would open the image in sequential mode, then use `copy_memory()` to make an in-memory copy of the whole thing. You should be able to call `inplace()` on that without forcing duplication.

**Comment by jcupitt** [comment]
I wouldn't use regions -- if you write to them, you are likely to break libvips caching.

Here's the sample program I used for testing, fwiw:


```C++
/* compile with:
 *
 * g++ -g -Wall draw.cpp `pkg-config vips-cpp --cflags --libs`
 *
 * run with eg.:
 *
 * ./a.out ~/pics/x.tif x.tif[compression=ccittfax4,squash] ~/pics/k2_mono.jpg
 */

#include <stdlib.h>
#include <vips/vips8>

using namespace vips;

int
main( int argc, char **argv )
{
        if( VIPS_INIT( argv[0] ) )
                vips_error_exit( NULL );

        VImage main = VImage::new_from_file( argv[1], 
                VImage::option()->set( "access", VIPS_ACCESS_SEQUENTIAL ) );
        VImage tiny = VImage::new_from_file( argv[3] );

        printf( "calling vips_image_inplace() ...\n" );
        main = main.copy_memory();
        if( vips_image_inplace( main.get_image() ) )
                vips_error_exit( NULL );

        printf( "calling 1000 insert operations ...\n" );
        for( int i = 0; i < 1000; i++ ) {
                int left = rand() % main.width();
                int top = rand() % main.height();

                if( vips_draw_image( main.get_image(), tiny.get_image(), 
                        left, top, NULL ) )
                        vips_error_exit( NULL );
        }

        printf( "writing to output ...\n" );
        main.write_to_file( argv[2] );

        return( 0 );
}
```

**Comment by jcupitt** [comment]
Regarding `vips_image_inplace()`, this is called for you by the draw operations, so there's no need to call it yourself.

**Comment by MathemanFlo** [comment]
Thank you very much, it worked like a charm and saved me a lot of time.
