### ISSUE TITLE
filename size limitation?

### ISSUE THREAD

**Issue by bigfatfrog67** [libvips/libvips#1613]
Trying this on hundreds of scanned maps I have to make them zoomable online and it's work brilliantly except when it hits some extra long filenames such as: `j-m-dent-and-sons_atlas-of-ancient-and-classical-geography_1912_armenia-colchis-iberia-albania-etc-eastern-turkey-armenia-azerbaijan-georgia_3414_2114_600.jpg`.

Here's the command and the output:

```
c:\vips-dev-8.9\bin\vips dzsave j-m-dent-and-sons_atlas-of-ancient-and-classical-geography_1912_armenia-colchis-iberia-albania-etc-eastern-turkey-armenia-azerbaijan-georgia_3414_2114_600.jpg j-m-dent-and-sons_atlas-of-ancient-and-classical-geography_1912_armenia-colchis-iberia-albania-etc-eastern-turkey-armenia-azerbaijan-georgia_3414_2114_600 --suffix .jpg[interlace=1]

** (vips.exe:8348): CRITICAL **: 12:28:05.241: gsf_outfile_new_child_full: assertion 'outfile != NULL' failed

** (vips.exe:8348): CRITICAL **: 12:28:05.252: gsf_outfile_new_child_full: assertion 'outfile != NULL' failed

** (vips.exe:8348): CRITICAL **: 12:28:05.257: gsf_outfile_new_child_full: assertion 'outfile != NULL' failed
```

If I shrink the filename down all is OK.  My Windows 10 is configured to accept extra long filenames but still it fails. Is there some internal limit to vips?

Thanks

Jonathan
p.s. You can check out my maps at www.hipkiss.org :-)

**Comment by jcupitt** [comment]
Hello @bigfatfrog67,

There's a Windows limit of 260 characters. You need to enable long path support at a system level (sounds like you've done this), and also enable long path support for the application (it's in the manifest somewhere I think), and (I think) also use a long-path-aware API (ie. not the Windows posix compat API). And even if you do all that, you are still likely to be bitten when some other program you use to work on the files does not have this option enabled. I think I would just stay within the limit :(

On Windows, I would generate a zip rather than generating files. Try:

```
vips.exe hugefile.jpg x.zip
```

That should (I think?) dodge the limit, and writing a zip is *much* faster (4x faster?) than writing to NTFS. It'll be more convenient for uploading to your server as well.

**Comment by bigfatfrog67** [comment]
Thanks, I had done all that.

Just tried: `c:\vips-dev-8.9\bin\vips dzsave j-m-dent-and-sons_atlas-of-ancient-and-classical-geography_1912_armenia-colchis-iberia-albania-etc-eastern-turkey-armenia-azerbaijan-georgia_3414_2114_600.jpg j-m-dent-and-sons_atlas-of-ancient-and-classical-geography_1912_armenia-colchis-iberia-albania-etc-eastern-turkey-armenia-azerbaijan-georgia_3414_2114_600.zip --suffix .jpg[interlace=1]`   and it works with no problem. As you can see it's still using the long filename so how come it doesn't trip up when zipped but it does when not?

**Comment by jcupitt** [comment]
The problem is the length of the whole path, not the lenth of the filename, so eg. writing to `c:\vips-dev-8.9\bin\vips\j-m-dent-and-sons_atlas-of-ancient-and-classical-geography_1912_armenia-colchis-iberia-albania-etc-eastern-turkey-armenia-azerbaijan-georgia_3414_2114_600_files\13\12_14.jpg`. 

`dzsave` uses a library called libgsf to write the zips and the tiles, and that library (I would guess) does not support the long filename win32 API.

**Comment by jcupitt** [comment]
Your site looks nice, btw. I suppose you'll be able to scan at higher res if you use openseadragon for the viewer.

Some friends of mine made this: https://easyzoom.com you could consider that as well. You can upload huge images to their system and they'll host and display them for you. You can embed their iframe in your site and it looks like you're hosting the image. It uses vips behind the scenes.

**Comment by bigfatfrog67** [comment]
Thanks again, I've decided to rename all my files to be shorter ID based rather than descriptive. All the metadata is in EXIF anyway so nothing should be lost.

I'll take a look at easyzoom.com.
