### ISSUE TITLE
Can vips read/write TIFF format using multiple threads ?

### ISSUE THREAD

**Issue by boxerab** [libvips/libvips#1623]
I am currently using `libtiff`, but it is a damn shame that read/write is single threaded while most cores are sitting idle.

**Comment by jcupitt** [comment]
libtiff is single threaded, unfortunately, so there's not much libvips can do.

It will do the libtiff calls in a background thread, so that should be the only single-threaded part. It can do read and write in separate threads too, so if you are processing:

```
read tiff -> compute -> write tiff
```

The decode will run in one thread, the compute will run in many threads, and the write will run in another thread.

**Comment by boxerab** [comment]
Thanks, John. Hopefully some day it will be reworked to use all cores.
