### ISSUE TITLE
membarrier system calls are crashing Google Cloud Run

### ISSUE THREAD

**Issue by kaisellgren** [libvips/libvips#1653]
It seems to me that libvips uses membarrier system calls?

`Container Sandbox: Unsupported syscall membarrier(0x8,0x0,0x0,0x2a37cf92efc0,0x2a37cf92fab0,0x7). It is very likely that you can safely ignore this message and that this is not the cause of any error you might be troubleshooting. Please, refer to https://gvisor.dev/c/linux/amd64/membarrier for more information.
`

Google Cloud Run uses gVisor, which does not support `membarrier` system calls. Is there a way to add fallbacks to wherever these calls are being used in libvips? I'd really love to use libvips in my Google Cloud Run project! Loving it otherwise.

**Comment by jcupitt** [comment]
Sorry, I don't know what might be calling membarrier. It's not libvips itself.

I searched glib and didn't see it. ImageMagick uses openmp -- could that be the cause?

Perhaps you could use strace or gdb to try to get more information about the source. I don't know anything about gvisor :(

**Comment by kleisauke** [comment]
Is it possible that `g_once` is causing this? Perhaps merge request [GNOME/glib#1364](https://gitlab.gnome.org/GNOME/glib/-/merge_requests/1364) is relevant here.

**Comment by jcupitt** [comment]
Ah good strace testing. I searched glib 2.63 with:

```
$ find . -type f -exec grep -li membarrier {} \;
```

and found nothing. google found no interesting results for a search on `gvisor membarrier openmp` either. I think you'll need to do some more digging.

**Comment by kaisellgren** [comment]
I'll have to do some more research. I'll get back later.

**Comment by kleisauke** [comment]
I noticed this comment https://github.com/google/gvisor/issues/267#issuecomment-628593340 on the gvisor repository, indicating that you're using sharp. So, I also checked whether one of the pre-built binaries provided by sharp uses the membarrier symbol. 

I append `-Wl,-trace-symbol=membarrier` to the `LDFLAGS` here:
https://github.com/lovell/sharp-libvips/blob/f1a31250fc01fd6970487adfc5ad69b05ee94fec/build/lin.sh#L18

Which instructs the linker to print additional details where membarrier is defined, and where membarrier is used. After building the pre-built binaries with this trace option, I can conclude that none of the dependencies uses the membarrier symbol. 

The trace itself does work since I saw these reports when I linked with `-Wl,-trace-symbol=open`:
```
../src/.libs/libfontconfig.a(fccompat.o): reference to open
/target/lib/libfreetype.a(ftsystem.o): reference to open
/target/lib/libexpat.a(xmlparse.o): reference to open
/lib64/libpthread.so.0: definition of open
…
```

The above linked issue mentions that these problems can occur on an Alpine-based Node.js image, do you use that? If so, you could try a non-Alpine base image.

**Comment by kaisellgren** [comment]
You're right. It has to do with the Alpine base image. I'm happy I get to continue using libvips :-)

For future reference to others: your issue with membarrier is likely to come from elsewhere.

Thank you guys!

**Comment by lovell** [comment]
@kaisellgren sharp's Node.js 10 musl-based Linux CI is pinned to the `node:10.17.0-alpine3.9` tag for the same reason, as the use of `membarrier` is not allowed within Travis CI's Docker environment.

https://github.com/lovell/sharp/blob/dad7f1e1f624439c57ba790d0423c76122ce81bf/.travis.yml#L52

**Comment by ytnobody** [comment]
Yesterday I encountered this issue on Google Cloud Run + `golang:1.12-alpine`.

https://github.com/google/gvisor/issues/1739#issuecomment-673861090
