### ISSUE TITLE
heifsave: Unsupported compression

### ISSUE THREAD

**Issue by GrandArth** [libvips/libvips#1738]
I downloaded the vips-dev-w64-all-8.9.2 release, move it to `C:\vips-dev-8.9` and add `C:\vips-dev-8.9\bin` to `PATH`.
I tried the following set of commands using the commandline tool (all heic related command) but i get the same error `heifsave: Unsupported compression`.

```
 vips heifsave 1.png  1.heif
 vips heifsave 1.png  1.heic
vips resize 000.heic aaa.heic 0.5 --kernel linear

```

I went trough the documentation but failed to find an answer. 
Any help or suggestion will be appreciated.
Thx in advance.

**Comment by GrandArth** [comment]
Reading heic is generally fine but any command invloves writing in heic format will end up in that error.

**Comment by jcupitt** [comment]
Hello @GrandArth,

The HEIC encode library is part of ffmpeg and is GPL. This means we can't safely distribute a compiled binary, since every program that linked to libvips would then also become GPL. There are also a range of tricky issues around software patents as well, of course.

You'll need to build libvips yourself if you need HEIC encode support.

**Comment by GrandArth** [comment]
> 
> 
> Hello @GrandArth,
> 
> The HEIC encode library is part of ffmpeg and is GPL. This means we can't safely distribute a compiled binary, since every program that linked to libvips would then also become GPL. There are also a range of tricky issues around software patents as well, of course.
> 
> You'll need to build libvips yourself if you need HEIC encode support.

Oh i see.
Thx for the intel.
