### ISSUE TITLE
 libvips.so.42: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by rajkumarks7** [libvips/libvips#1814]
**Describe the bug**
i am using the bimg getting this error how to solve it.
./workahub: "error while loading shared libraries: libvips.so.42: cannot open shared object file: No such file or directory"
when i run the exe from the terminal in Ubuntu i am getting the above error 

**Environment**
(please complete the following information)
 - OS: Ubuntu 18.04
 - Vips: 8.10 
 - Go:1.14

**Comment by lovell** [comment]
Hi, please can you provide more information about how you've installed libvips.

Did you see https://github.com/h2non/bimg#installation ?

What does "when i run the exe" mean?

**Comment by rajkumarks7** [comment]
okay give me a min

**Comment by rajkumarks7** [comment]
like i followed the whole documentaion of the libvips

i built a exe for my program which use the bimg for processing the thumbnails

**Comment by rajkumarks7** [comment]
> Hi, please can you provide more information about how you've installed libvips.
> 
> Did you see https://github.com/h2non/bimg#installation ?
> 
> What does "when i run the exe" mean?
actually i developed a desktop application i am using bimg for the processing of the image

yes i used below link for installation
https://libvips.github.io/libvips/install.html

**Comment by giovannibonetti** [comment]
I'm having the same problem, but I can share my setup more easily since we use Docker here

## Problem

Reported by Sentry and the Ruby library (ruby-vips 2.0.17):

![Screen Shot 2020-09-21 at 11 09 34](https://user-images.githubusercontent.com/3451581/93777304-f809a980-fbfa-11ea-9460-0f383c69949c.png)

Our Dockerfile (based on [prettotech/ruby-jemalloc/2.7.1](https://hub.docker.com/layers/prettotech/ruby-jemalloc/2.7.1/images/sha256-a1b10f250c4803748a7e657202f49d1c0866d2f98ef56b58381e7617e3d163b5?context=explore)) has the following instructions to install Libvips:

```Dockerfile
# Download and install libvips
# https://libvips.github.io/libvips/install.html#building-libvips-from-a-source-tarball
# https://github.com/janko/image_processing/blob/master/install/libvips.sh
ARG VIPS_VERSION=8.10.1
RUN mkdir -p $HOME/vips-$VIPS_VERSION \
    && cd $HOME/vips-$VIPS_VERSION \
    && wget -q https://github.com/libvips/libvips/releases/download/v$VIPS_VERSION/vips-$VIPS_VERSION.tar.gz \
    && tar xzf vips-$VIPS_VERSION.tar.gz \
    && cd vips-$VIPS_VERSION \
    && ./configure > /dev/null 2>&1 \
    && make > /dev/null 2>&1 \
    && make install > /dev/null \
    && ldconfig \
    && rm -Rf $HOME/vips-$VIPS_VERSION \
    && cd
```

We have been using Libvips for over an year, and have upgraded to 8.10.1 on September 4th (17 days ago), but started having this error only today.
