### ISSUE TITLE
Segfault / access violation while creating histogram of alpha band with C API

### ISSUE THREAD

**Issue by zakimano** [libvips/libvips#1820]
I want to use the C libvips api from a (win64) C++ project to analyze the alpha band of some images I read from disk - specifically I want to be able to tell if the image has transparent pixels, the use case is very similar to issue #1535 
The reason I went with the C api is simplicity in the build / linking process, and it worked out well, but now I'm stuck on the following issue:
`maps.at(TT_DIFF).path_full` is a `std::string` containing the absolute path to the image to read.
To my knowledge `p_img` works as expected, the image gets read properly.
```c
VipsImage* p_img = vips_image_new_from_file(maps.at(TT_DIFF).path_full.c_str(), NULL);
if (p_img != NULL && vips_image_hasalpha(p_img))
{
	VipsImage hist;
	VipsImage* p_hist = &hist;
	vips_hist_find(p_img, &p_hist, 3);
	
	// do stuff with (p_)hist
	
	// g_object_unref(p_hist);
}
g_object_unref(p_img);
```
My problem is that I get a segfault (access violation) on the line with `vips_hist_find(p_img, &p_hist, 3);`.
What am I doing wrong here? I'm sorry I can't paste the entire file here for testing, hopefully this is enough to work out my error.

Thanks for your help!

**Comment by jcupitt** [comment]
Hi @zakimano,

I think you're calling `hist_find` incorrectly. The pattern should be:

```c++
VipsImage *image;

if (!(image = vips_image_new_from_file(filename, NULL))) {
  error_handling();
}

if (vips_image_hasalpha(image)) {
  VipsImage *hist;

  if (vips_hist_find (image, &hist, 3, NULL)) {
    error_handling();
  }

  // do stuff with hist

  g_object_unref (hist);
}

g_object_unref (image);
```

If you turn on compiler warnings it should alert you to stuff like this.

**Comment by jcupitt** [comment]
That will fail if you give it a mono image with alpha, of course, but perhaps that's not a problem.

You won't be able to link against the pre-compiled C++ API with MSVC since C++ programs must use the same compiler and compiler version everywhere. But you can copy the libvips C++ API into your project and build it there. It's only a small amount of code and very simple to compile. This is what sharp (the libvips node binding) does.

libvips has unref pools, which can make C code like this easier. 

https://libvips.github.io/libvips/API/current/VipsObject.html#vips-object-local-array

**Comment by zakimano** [comment]
Thank you for the quick response, I was indeed calling `vips_hist_find` incorrectly.
The code works with the above fix.
Mono images are outside of my scope of support here, and thanks for the heads up on the unref pools.
