### ISSUE TITLE
Gif images with transparent background converted incorrectly after ThumbnailImage

### ISSUE THREAD

**Issue by lofcz** [libvips/libvips#1821]
**Describe the bug**
after applying `ThumbnailImage(w: x, h: y, size: "force")` to a GIF with transparent background, image is incorrectly processed. GIFs with non-transparent background work well. In case I don't create a thumbnail and just save with `Magicksave` GIFs are ok. Still might be related to this: https://github.com/ImageMagick/ImageMagick/issues/2491

Example 1:
![7f5bfdba-ca26-4a1f-9d43-d9d621179d9d](https://user-images.githubusercontent.com/10260230/93533501-53aa0d80-f943-11ea-90d1-e6e70eca2e29.gif)
![7f5bfdba-ca26-4a1f-9d43-d9d621179d9d_128_128](https://user-images.githubusercontent.com/10260230/93533502-54db3a80-f943-11ea-8572-cbba72075971.gif)

Example2:

![11ea7283-7fd5-4ee2-906c-0b364b942615](https://user-images.githubusercontent.com/10260230/93533532-6e7c8200-f943-11ea-9430-8276e7f1152a.gif)
![11ea7283-7fd5-4ee2-906c-0b364b942615_128_128](https://user-images.githubusercontent.com/10260230/93533535-6fadaf00-f943-11ea-88ea-762ee9341f63.gif)

**Environment**
 - OS: Windows 10, latest insider build
 - Vips: 8.10 (using wrapper for .net)

_PS: you must love these reports around GIFs, sorry about bringing up another one_

**Comment by jcupitt** [comment]
Hi @lofcz,

Yes, GIF rendering errors are my favourite bugs :-( 

But I think this time libvips is maybe OK. I tried:

```
vipsthumbnail sunset.gif[n=-1] -s 256 -o x.gif
```

With 8.10 and I see:

![x](https://user-images.githubusercontent.com/580843/93560399-fbdac900-f979-11ea-840a-dc51aca1c630.gif)

So yes, I'd guess it was a problem with imagemagick saving the GIF, rather than libvips loading it. I'm using ubuntu20.04, which is on imagemagick 6.9.10.23.

If that's correct, this should be fixed in the windows build in the next release.

**Comment by jcupitt** [comment]
Yes, I'd guess 8.10.2 is coming in a week.

You can always build yourself, of course:

https://github.com/libvips/build-win64

Install docker, then `./build.sh 8.10 all` to make a zip of the windows binaries.

**Comment by kleisauke** [comment]
You could also download the binaries from https://github.com/libvips/build-win64-mxe/releases/tag/v8.10.1, it includes ImageMagick 6.9.11-29 which has a fix for this.

I'll prepare a PR to update ImageMagick in the official binaries.
