### ISSUE TITLE
Windows build of VIPSCC for vips with Python

### ISSUE THREAD

**Issue by ReeseMurdock** [libvips/libvips#185]
I am wondering if you know of an alternative source for the Windows build of the VIPSCC you reference here https://github.com/jcupitt/libvips/issues/92?  The drop box account it was being hosted in is currently suspended for too much traffic.

**Comment by Topochicho** [comment]
Thank you for this.  I am sorry I essentially abandoned this question.  Just so you know, all of my free time, and many hours I am supposed to be working on something else, now go into VIPS related issues.  

I had to build a proof of concept using the command line VIPS in order to get approval to keep working on VIPS and switch to version 8.  It caused a crap storm.  A crap storm of wedging the command line VIPS version into places that I will have to go back and make the python version work later. 

So, thank you again and I will, eventually, put this to good use.

**Comment by jcupitt** [comment]
Oh don't worry, but I would be interested to hear if you can get the new Python stuff working on Windows. I had a quick go at work, but I don't have admin on any of the Windows machines unfortunately. I ought to get IT to add me I suppose.
