### ISSUE TITLE
Add warnings API to libvips

### ISSUE THREAD

**Issue by tonimelisma** [libvips/libvips#1878]
**Is your feature request related to a problem? Please describe.**
Unlike other image processing libraries like ImageMagick or Python's PIL, libvips is often happy to process corrupt or semi-corrupt images without giving an error. Instead it gives a warning.

However, this warning is only logged via glib logging, not returned atomically in context with the libvips operation which caused the warning. Unlike errors, warnings with libvips are not returned and thus the host software is unaware of warnings.

The current option is that libvips logs those warnings. However, the host software might want to abort/error on warnings, skip the file, ask the user what the user prefers to do in light of the warnings, etc. These are all impossible to do.

What's more, the logging is inefficient in most cases. A web backend might want to return an error code to the frontend, yet the logging messages can not be reliably catched and related to the operation so this is impossible. I'm currently building a CLI batch program that processess thousands of images. The only way in my case to make the logging relevant so the end user realises what file the warnings relate to, would be to print each filename to the console as it's being processes - and even this wouldn't work due to concurrency issues in a multithreaded program.

The only hack to catch warnings related to a libvips operation from the host software is to create a glib logging handler, push warnings to a stack, clear the stack, do the libvips operation, and check if any logging messages of severity warning or above have appeared on the stack.

However, this doesn't work because of concurrency issues in a multithreaded program.

**Describe the solution you'd like**
Not sure what the best design pattern here would be.

A small change could be a flag to libvips to error on warnings, so it would behave more like other software and be stricter in its inputs. However, this doesn't solve the issue.

Another change would be to simply error more, have a wider variety of error codes, and let the host software figure out what it wants to do with each error. The host software can then be built with the logic to figure out what to do with which error.

The best solution would be instead of an error code to return a struct or something similar, that has proper semantics on whether either an error or warning appeared, and proper machine-parsable coding for the host software to figure out what the error was so it can also decide what it wants to do.

**Comment by tonimelisma** [comment]
For additional context and several users' feedback from the sharp library, see [https://github.com/lovell/sharp/issues/607](https://github.com/lovell/sharp/issues/607)

**Comment by jcupitt** [comment]
Hi @tonimelisma,

Thanks for looking at this. Have you seen the `fail` flag? It makes loaders strict rather than permissive:

https://libvips.github.io/libvips/API/current/VipsForeignSave.html#VipsForeignLoad--fail

It works like this:

```
john@kiwi:~/pics$ vips copy broken.jpg x.jpg

(vips:1074257): VIPS-WARNING **: 11:16:08.296: read gave 2 warnings

(vips:1074257): VIPS-WARNING **: 11:16:08.296: VipsJpeg: Premature end of JPEG file

john@kiwi:~/pics$ vipsheader x.jpg
x.jpg: 1024x768 uchar, 3 bands, srgb, jpegload
```

So default behaviour is permissive. If you add `fail`:

```
john@kiwi:~/pics$ vips copy broken.jpg[fail] x.jpg

(vips:1074275): VIPS-WARNING **: 11:16:25.073: error in tile 0 x 192

(vips:1074275): VIPS-WARNING **: 11:16:25.073: error in tile 0 x 200
VipsJpeg: Premature end of JPEG file
VipsJpeg: out of order read at line 192
```

Now there's an error return and the output file is not complete. It might help fix some of the problems you are having. There's also room for debate about what counts as an error and what counts as a warning --- for example, should a PNG image with an embedded CMYK profile fail?

One improvement might be to add an optional output parameter to loaders with (as you say) some kind of struct summarizing the errors and warnings.

**Comment by tonimelisma** [comment]
Thanks - the fail option actually helps a lot, although it only catches a part of the warnings, and only relates to loading files.

Having now used vips "in the wild" with tens of thousands of images there's a lot of funky warnings I get with different operations that I'd feel like catching in my host software, and dealing with them somehow.

I understand the struct approach is perhaps not very idiomatic for C, but in the case of image processing we're talking about more art than science - it's impossible for libvips to draw a black and white line saying "this is an error and this isn't". I feel like the host software should still get a more fine-grained understanding of any non-error issues that happened in any of the operations.

**Comment by jcupitt** [comment]
Yes, the range of terrible files you comes across in the wild is really eye-opening. TIFF is especially bad, since you can write almost anything as a TIFF file.

It will be hard to avoid being platform-specific. For example, libvips can use either libpng or libspng for PNG load, and they have different ideas about what counts as an error and a warning. The libvips user will need to know how libvips has been configured.

Can you give some examples of bad files you'd like to be able to detect? The two main cases (in my experience) are truncated files and bad colour profiles, both of which you ought to be able to handle (to a degree, anyway) with the current API.

**Comment by tonimelisma** [comment]
I'm closing this for now. Once I have proper examples that aren't catched by the fail flag I'll come back.
