### ISSUE TITLE
Libvips fails to load the file attached

### ISSUE THREAD

**Issue by jaubourg** [libvips/libvips#1901]
As reported in #1888.

I'm getting a: `source: bad seek to 1272289` when loading the following heic file:

[IMG_2631.zip](https://github.com/libvips/libvips/files/5593259/IMG_2631.zip)

It's from "the wild" so I have no clue how it was created/saved.

I'm using a custom build with:

libde265 1.0.8
libheif 1.9.1
libvips 8.10.2
x265 3.4

**Comment by jcupitt** [comment]
Thanks for the report @jaubourg 

I see this with git master libvips too, with git master libheif.

The `heif-convert` example program can read it, so it seems to be something weird in the seek / read implementation in libvips `heifload.c`.

**Comment by jaubourg** [comment]
Good luck seeking the source of the problem ;)

**Comment by ddennedy-gpsw** [comment]
I am experiencing the same error with the attached HEIC in git master branch:
```
root@f75703e5ec86:/# vips --version
vips-8.11.0-Wed Nov 25 19:30:27 UTC 2020
root@f75703e5ec86:/# cd /mnt
root@f75703e5ec86:/mnt# vipsthumbnail IMG_5861.HEIC 
vipsthumbnail: unable to thumbnail IMG_5861.HEIC
IMG_5861.HEIC: bad seek to 1532687
```
 I tried versions 8.9.2, 8.10.1, 8.10.2 fails on #1861, and master branch today Nov. 25. I also confirmed that `heif-convert` from libheif 1.6.1 in ubuntu:20.04 succeeds as well as macOS 10.15. Quite likely it is the same bug, and here is another sample with which to test a fix. 
[IMG_5861.HEIC.zip](https://github.com/libvips/libvips/files/5598966/IMG_5861.HEIC.zip)

**Comment by ddennedy-gpsw** [comment]
Tried to help debug this today, but it is a pain on macOS due to using gcc for some dependency compiled with gcc -fopenmp, lldb not stopping on breakpoints, and gdb not easy to get working on macOS because it is unsigned. Anyways, I added some logging. The displayed error occurs inside `vips_foreign_load_heif_wait_for_file_size()` (libheif callback) on `target_size` is 8 > file size. Using libheif v1.9.1. The original poster's image fails in the same way. libheif examples do not use this reader interface and instead use `heif_context_read_from_file()`. Maybe this bad seek is actually OK and not an error because it tells libheif EOF. Processing and logging continues beyond that bad seek.

**Comment by lovell** [comment]
I had a quick look at this - I think it might be a libheif feature/bug.

Running `heif-info IMG_2631.HEIC` at the command line I can see `heif::BoxHeader::parse()` attempts to read 8 bytes beyond the end of the file here:

https://github.com/strukturag/libheif/blob/b0dc62709f1f066781e6b065d307a95826737554/libheif/box.cc#L186-L194

This correctly generates a `heif_suberror_End_of_data` error but this is ignored internally, so my best guess would be that libheif is using this error condition as a way to detect if there are any more boxes to read.

**Comment by jcupitt** [comment]
Huh interesting, yes I saw the same strange behaviour when I tried tracing the weird seek.

I tried making the vips seek method silently ignore bad seeks, but it didn't fix it. I'm unsure what the best solution is.

**Comment by ddennedy-gpsw** [comment]
It still prints a bad seek error, but like I said that was a red herring. It is not obvious to me how to prevent that. I found this problem by setting a breakpoint at the beginning of most functions in `heifload.c`. Then, stepping through until I saw it reach an unexpected error.
