### ISSUE TITLE
Unexpected result from ppmsave / interpretation of image bands

### ISSUE THREAD

**Issue by ewelot** [libvips/libvips#1910]
I am trying to convert a set of three monochrome FITS images (bitpix -32) representing red, green and blue color channels to a PPM image (16bit). The FITS files were created by the software [skymaker](http://astromatic.net/software/skymaker). This is what I did so far:
```
vips bandjoin "red.fits grn.fits blu.fits" x.cube.v
vips cast x.cube.v x.cube16.v ushort
vips ppmsave x.cube16.v x.ppm

```
The intermediate image x.cube16.v seems to be fine and  contains values truncated to 16bit integer range matching those expected from input FITS data. Unfortunately the output image x.ppm does not match expectations, instead it consists of three identical channels all of which matching the first band of x.cube16.v. I suspect that the reason for this is a difference in the interpretation of image bands: the program vipsheader displays "b-w" in case of x.cube16.v but "rgb16" in case of x.ppm.

Is this on purpose? How do I have to modify my code to get the desired results?
Thanks for advice,
Thomas
(btw, I am using the patched ppmsave/ppmload including latest fixes) 

[fits32sky.zip](https://github.com/libvips/libvips/files/5622020/fits32sky.zip)

**Comment by jcupitt** [comment]
Hi @ewelot,

libvips is interpreting your three-band ushort image as monochrome plus two alpha channels. ppm does not support alpha, so they are being dropped, and just the first channel used to make an RGB for save.

You need to set the interpretation of the three band image as RGB instead. You can use:

```
vips copy in.v out.v --interpretation srgb
```

Or in Python (it'll be *much* quicker):

```python
r, g, b = [pyvips.Image.new_from_file(filename + ".fits") for filename in ["red", "grn", "blu"]]
rgb = r.bandjoin([g, b]).copy(interpretation="srgb")
rgb.ppmsave("something.ppm")
```

**Comment by ewelot** [comment]
Thanks for clarification and the python code snippet. Just one question regarding the latter: does the change of interpretation automatiically imply a data type cast to 16bit integer or is there a need for an additional step involving explicit casting?

**Comment by jcupitt** [comment]
"interpretation" is just a tag attached to the image hinting at how pixel values should be interpreted.  An image tagged as sRGB could have float pixels, for example, it's just that savers will expect values in the range 0 - 255 to mean black - white.

16-bit RGB has a separate interpretation value, since pixels are 0 - 65535. I should have written:

```
rgb = r.bandjoin([g, b]).copy(interpretation="rgb16")
```

Interpretation docs:

https://libvips.github.io/libvips/API/current/VipsImage.html#VipsInterpretation

There's a general introduction here:

https://libvips.github.io/libvips/API/current/VipsImage.html#VipsImage.description

**Comment by ewelot** [comment]
It is working fine now, thanks again!

**Comment by ewelot** [comment]
I'd like to ask few more questions regarding image data of float type:
- Which operations are involved when using the flag interpretation="rgb16" and writing the data to disk (e.g. using function ppmsave)? Is data first trimmed to the valid 0 - 65535 range and then rounded to integer by a floor operation?
- Is it any useful to cast data to ushort if there is no other arithetic operation before writing the output image?
- Is data still treated as float values when doing any subsequent arithmetic operation after setting the flag interpretation="rgb16"?

**Comment by jcupitt** [comment]
- Yes, save operations will use `cast` to trim images to the types supported by the saver. It can be useful to cast before things like tiffsave, since tiff supports float and even complex pixels, and you often don't want to save in that format.
- Yes, `interpretation` is just a hint about how pixel values should be interpreted. Very few operations (other than savers, colourspace conversion and image display) change behaviour depending on its value.

**Comment by ewelot** [comment]
When converting floats to integers does it apply the floor operation or is it using some kind of mathematical rounding? Is it the same behaviour when using either explicit conversion (e.g. using cast function) or implicit conversion by `interpretation="rgb16"` ?

**Comment by jcupitt** [comment]
`cast` has the same semantics as C -- straight truncation to nearest. You can use `image.rint()` if you need round to nearest.

**Comment by ewelot** [comment]
Thanks again!
