### ISSUE TITLE
Memory profiling for libvips

### ISSUE THREAD

**Issue by tonimelisma** [libvips/libvips#1929]
Libvips (via using govips) takes huge amounts of memory and doesn't free it.

*Can you explain expected memory usage for libvips and how I might about profiling it?*

To explain the situation, I've got a multi-threaded image processing app which uses govips which in turn uses libvips 8.10.2 on Ubuntu 20.10. The app is blazingly fast and within 1-2 minutes opens, processes and saves around 150 images. During this time the app grows memory usage to 1.6GB.

I've built go memory profiling to the program, which covers the program itself as well as the Go parts of govips, which reports only 3.2MB of memory being used at that stage.

I've also created debug hooks into govips, and govips garbage collection is active and it's closing all opened image reference shortly after they've been saved. I suspect the bug is with the govips cgo code which garbage collects the memory reserved by Go but doesn't free the malloc'd memory from libvips.

I ran valgrind's massif on the program to profile memory usage. After processing 10 images verrrry slowly the massif cli gave a SIGSEGV as too much stack was reserved:
[massif_clid.txt](https://github.com/libvips/libvips/files/5684725/massif_clid.txt)

At that stage, you can already see memory usage having grown from 200MB at startup to 400MB when having processed 10 iamges:
[massif_out.txt](https://github.com/libvips/libvips/files/5684719/massif_out.txt)

The pictures are all small JPEGs taken with an old smartphone, so maybe a couple hundred KB per picture. Operations are limited to resizing and cropping the images.

*1. Even if there's not any memory leaks, is it normal for libvips to use this much memory for such small images and rudimentary operations?*

*2. Do you have any recommendations on C tooling I could use to further debug libvips's memory usage and where it's coming from?*

**Comment by tonimelisma** [comment]
I get the exact same behavior on macOS as well.

**Comment by jcupitt** [comment]
Hi @tonimelisma,

Memory use should be low, if I understand what you are doing. For example, here's a small python benchmark:

```python
#!/usr/bin/python3

import sys
import pyvips

for filename in sys.argv[1:]:
    image = pyvips.Image.thumbnail(filename, 200, height=200)
    image = image.crop(10, 10, 100, 100)
    data = image.write_to_buffer(".jpg")
```

It's just thumbnailing each image, cropping to 100x100 pixels, and saving in memory as a jpg file. I can run it like this:

```
$ mkdir samples
$ for i in {0..1000}; do cp ~/pics/nina.jpg samples/$i.jpg; done
$ vipsheader ~/pics/nina.jpg 
/home/john/pics/nina.jpg: 6048x4032 uchar, 3 bands, srgb, jpegload
$ ls -l ~/pics/nina.jpg
-rw-rw-r-- 1 john john 1220314 May  8  2018 /home/john/pics/nina.jpg
```

So that's a directory with 1,000 copies of a 6k x 4k jpg (1.2mb) of my daughter. If I run that py on this five year old laptop, I see:

```
$ /usr/bin/time -f %M:%e ./toni.py samples/*
79380:51.10
```

So it took ~50s and peak memory use was ~80mb.

Python is reference-counted, so resources are freed as soon as they are no longer being used, there's no need to wait for the GC to run. If you are using a language with a mark-sweep or generational GC, you can expect mem use to be higher unless you force the GC to run.

ruby-vips forces a GC run after every vips pipeline execution. Ruby has a generational GC, so this is very cheap (1ms?). If Go does not have a generational GC this might not be practical. Running the GC after every operation would at least check that the problem is GC frequency.

Many languages (eg. C#) have a way for the library to hint the memory "weight" of a native pointer to the GC. If the GC knows that a certain native reference is expensive, it will prioritize freeing that object. Does Go support hints like this? It might be worth investigating.

You need a detailed understanding of libvips' reference counting rules and the host language GC to make a binding that doesn't leak objects -- it's really quite tricky, and a complete pain to debug. 

I don't know anything about these Go bindings, but it might be worth double-checking that you have no ref leaks. Run with the env var `VIPS_LEAK` set to 1 and libvips will print a table of active objects on program termination. This should (obviously) be empty.

**Comment by jcupitt** [comment]
I changed the label to "question", since this is almost certainly an issue somewhere else in your stack.

**Comment by jcupitt** [comment]
Oh, there's also memory fragmentation. It might be worth testing with something like jemalloc as well.

**Comment by tonimelisma** [comment]
Thanks for this John. Can you help translate the most important parts:
```
3399 VipsArea alive
(...)
memory: 3613 allocations, 576912592 bytes
files: 2 open
memory: high-water mark 633.81 MB
error buffer: source: bad seek to 1442575
source: bad seek to 2690359
source: bad seek to 1442575
```
What does 3399 refer to?

Does 3613 allocations mean that's the number of OPEN allocations in the end or TOTAL allocations done during the lifetime of govips? I'm confused by the fact there's a huge amount of allocations of only 40-80 bytes, what might these be related to?

I'm also confused by the amount of operations, the attached log has 11.8k lines although there were only 20 images, opened twice, and a handful of operations for each?

What might the bad seeks at the end refer to?

Attached is the full debug log:
[vips_log.txt](https://github.com/libvips/libvips/files/5685136/vips_log.txt)

**Comment by jcupitt** [comment]
`VipsArea` is a thing used to represent ref-counted areas of memory. They can be ICC profiles, matrices, arrays, etc., though not images. The number is the number of open allocations at program exit.

Yes, 3613 is the number of mallocs without a matching free. 

An operation can leave many objects in the log, so yes, I'd expect reference leaks to be large.

I'm not sure about the bad seeks. There was a bug in HEIC read, could that be it? It's fixed in 8.10.3.

Debugging reference leaks is the second worst job in programming (debugging race conditions is the worst). I usually start with a minimal test case and very slowly add complexity.

I would try calling `black` and work up from there, eg. 

```python
import logging
logging.basicConfig(level=logging.DEBUG)

import pyvips

image = pyvips.Image.black(10, 10)
image = None
```

That'll create a black image, then drop the reference. It will only create the image -- no pixels will be generated. If a Go equivalent exits with no reference leaks, you are off to a good start.

**Comment by jcupitt** [comment]
Do you know Python? Reading pyvips would be a good way to see how libvips reference counts should be handled.

The ruby binding is probably closer to Go (a generational mark-sweep collector), but Ruby is significantly harder to read when you start doing something complicated.

An alternative would be to write your image processing code in python and shell out to that from Go. At least you'd avoid having to debug ref counting issues.

**Comment by jcupitt** [comment]
There's a chapter in the docs about binding libvips:

https://libvips.github.io/libvips/API/current/binding.md.html

It has a simple C example showing how to call an operation and what needs reffing and unreffing at every stage. Hopefully the Go binding is doing something like that.

**Comment by tonimelisma** [comment]
Thanks John. After our latest release we had tried some "hacky" low-level optimisations which were binding the C data structures directly to Golang data structures which the Golang garbage collection didn't understand, and thus didn't free. I removed those and got the memory leak dump to show `memory: 0 allocations, 0 bytes` which is great.

However, your last link about the bindings was great. In Go we integrate with C libraries by using cgo which is basically a set of low-level interfaces that translate between native data types and functions in C and Go. We get type safety etc. In this case, we've just written C code which encapsulates the libvips APIs.

I'm confused about the part which says we should refrain from using the high-level C APIs, due to var args. With cgo, I fail to see what the risk or issue with varargs is - we can use them natively and we check on the Go side which parameters the host is supplying etc. What's the problem here and should we go through the pains of refactoring govips to use the low-level C APIs?

I'm hesitant to refactor as govips is covering about 80% of libvips functionality and it's got wide production use on several popular services (e.g. wix.com), so we want to keep it as stable as possible.

**Comment by jcupitt** [comment]
Ah, good it's working now.

The varargs stuff is painful to bind because it's not all represented in the C headers, and therefore it's not all typesafe -- for example, the types of optional arguments are not exposed to C.

If you use the lower-level GObject API, everything is type checked at runtime. For example, you can't crash the C++ binding by passing the wrong type as an argument, and types will be coerced if possible (eg. ints will be automatically promoted to float, strings will be turned into their enum values, and so on).

The lower level API also supports run-time introspection. The C++ binding lets you call any libvips operation, even ones for which there are no C or C++ headers. This means you don't need to change or regenerate the binding when you change the libvips version.

The C API is supposed to be convenient for C programmers, not for language bindings. It is itself a thin layer over the real GObject API.

... but of course if it's working for you, then that's great and you'll save yourself a week's work.

**Comment by jcupitt** [comment]
Oh, and if you write a GObject binding using introspection, you'll automatically get 100% of the libvips API, and it'll automatically update when new features are added to libvips. No more maintenance! We do this in part because it means we can decouple libvips versions from the versioning of the ruby, php, python, lua, node, C++ etc. etc. bindings.

**Comment by tonimelisma** [comment]
Oh, right, of course, C doesn't do varargs with proper type safety.

Implementing the GObject binding sounds like a great approach but unfortunately we've already gone down the other path. Considering govips is working well and we don't have manpower to refactor it just for the sake of reducing technical debt we're stuck on this path for the time being.

I don't know how you do it John, but you're without doubt the most friendly and helpful open source maintainer I've met 😄
