### ISSUE TITLE
update librsvg to use rsvg_handle_render_document()

### ISSUE THREAD

**Issue by jcupitt** [libvips/libvips#2296]
It seems librsvg no longer supports rsvg_handle_render_cairo() plus a clip rect to render large SVGs. Instead, you must now use rsvg_handle_render_document().

See https://github.com/libvips/libvips/discussions/2295

**Comment by jcupitt** [comment]
It seems librsvg have removed support for large output images, unfortunately.

```rust
impl From<cairo::Error> for Error {
    fn from(s: cairo::Error) -> Self {
        match s {
            cairo::Error::InvalidSize => Self(String::from(
                "The resulting image would be larger than 32767 pixels on either dimension.\n\
                 Librsvg currently cannot render to images bigger than that.\n\
                 Please specify a smaller size.",
            )),
            e => Self(format!("{}", e)),
        }
    }
}
```

I'll open an issue upstream.

**Comment by jcupitt** [comment]
After some investigation it seems unfixable.

I'll update svgload to use `rsvg_handle_render_document()`, but images larger than 32k will never work.

**Comment by kleisauke** [comment]
It looks like this limit is due to the use of 16.16 fixed point in pixman's trapezoid rasterizer, see:
https://lists.cairographics.org/archives/cairo/2009-July/017868.html
https://github.com/freedesktop/cairo/blob/929262dd54ffae81721ffe9b2c59faa7b045c663/src/cairo-image-surface.c#L59-L62

This limit was introduced in `rsvg-convert` with commit https://github.com/GNOME/librsvg/commit/90779ad40f9a7d1d6ba294e663973ff9c895d4e0, but it looks like I'm still able to convert this 65536 x 65536 SVG image using the vips command line utility.
```xml
<?xml version="1.0" encoding="UTF-8"?>
<svg xmlns="http://www.w3.org/2000/svg" width="65536" height="65536">
</svg>
```
```
$ vips copy big.svg x.png
```

**Comment by jcupitt** [comment]
Yes, I came across a few comments around this too. I think another issue is clipping: cairo uses 16.16 as well and librsvg needs to walk the tree with a cairo bounding box to find the visible parts of the drawing. These calculations can overflow even if the viewport is within the 32k limit.

librsvg 2.40.19 will render simple drawings larger than 32k if you scale/translate/clip, but complex drawings start to show a lot of clipping errors :( I suppose this is why they now throw an error.
