### ISSUE TITLE
Autorot not working on specific images

### ISSUE THREAD

**Issue by brenogazzola** [libvips/libvips#2338]
## Bug report
For specific images `autorot` is removing the exif tag but not actually rotating the image. The example below is the fixture that Rails uses to test vips/image magick in ActiveStorage.

**To Reproduce**
```
$ cd ~/Desktop
$ wget https://github.com/rails/rails/raw/main/activestorage/test/fixtures/files/racecar_rotated.jpg
$ exiftool racecar_rotated.jpg | grep Orientation
=> Orientation: Rotate 90 CW
$ vips autorot racecar_rotated.jpg racecar.jpg
$ exiftool racecar.jpg | grep Orientation
=> Orientation: Horizontal (normal) 
```

**Expected behavior**
Image is no longer rotated

**Actual behavior**
Finder thumbnail displays the image not rotated, but if you open on Preview or Pixelmator the image will still be rotated

**Screenshots**
![vips-autorot-bug](https://user-images.githubusercontent.com/1793280/124611084-7e6c4080-de47-11eb-9ac4-2c22bc25dcab.jpg)

**Environment**
(please complete the following information)
 - OS: MacOS 11.4
 - Vips: vips-8.11.1-Tue Jun 29 07:30:12 UTC 2021

**Comment by jcupitt** [comment]
Hi @brenogazzola,

This is a very confusing test image. It claims to be rotated (orientation 6), but in fact the real pixels are upright (!!). Try opening the image in a viewer which does not interpret the orientation tags.

When you run `vips autorot` on it, it flips it around and removes the tag (correctly), but now of course the image looks wrong, since the original pixels were correct before.

Anyway, I think it's all working correctly, this is just a strange test image.

**Comment by brenogazzola** [comment]
Got it. I'll open a PR in Rails to replace this image with one that is correct to avoid this confusion again. Thanks a lot @jcupitt.
