### ISSUE TITLE
Custom JP2K compression parameters

### ISSUE THREAD

**Issue by LionelArn2** [libvips/libvips#2724]
Hello :)

I see that saving and reading JP2K-compressed images on libvips makes use of `opj_set_default_encoder_parameters`.

Any chance we could change that to let the user choose his own compression parameters? Either by adding them in global variables, or in the parameters of the save/load methods?

Lionel

**Comment by jcupitt** [comment]
Hi @LionelArn2,

As I remember, I was reluctant to expose all the parameters, because there are so many. A large number of parameters are difficult to test and to maintain, and could cause compatibility problems with other jp2k encoders. 

Do you think there is a useful subset? Or would it be best to make parameters for all of them?

**Comment by LionelArn2** [comment]
Hi again, sorry for the late reply. 

I had some time to do a few tests with the OpenJPEG library to see which parameters could be impactful and I was actually surprised to see that I couldn't really see a difference in the image quality (visually) by varying the parameters other than Q. So there isn't much that can be improved from what you already offer, at least not for the images I tested.

The only significant factor I could see is the JPEG2000 tile size: at higher compression level, when we start to see compression artifacts, some edge effects appear around these tiles because they are each compressed independently. To minimize this effect, it would be desirable to have the tiles as large as possible (at the cost of increased memory consumption of course). In addition, it seems that the larger the tile size, the lower the compression time and the higher the compression ratio.

When saving the images as tiff with JPEG2000 compression, I noticed that you use the tiff tile size as the JPEG2000 tile size. Is this because we cannot set the JPEG2000 tile size to be larger than the tiff tile size?

**Comment by jcupitt** [comment]
I based the libvips jp2k save profile on the BM recommendations:

https://purl.pt/24107/1/iPres2013_PDF/An%20Analysis%20of%20Contemporary%20JPEG2000%20Codecs%20for%20Image%20Format%20Migration.pdf

For TIFF with jp2k, I just used one jp2k tile == one tiff tile, it seemed simplest. Otherwise you would have to expose two sets of tile size parameters, which I think most people would find very confusing.

As you say, you can't have jp2k larger than tiff tiles.

**Comment by LionelArn2** [comment]
Ok, thanks for the precision. Then I guess there isn't much room for improvement, the way you implemented it is already very good.
Thanks for your help!
