### ISSUE TITLE
Memory leak while copying VImage before drawing

### ISSUE THREAD

**Issue by MathemanFlo** [libvips/libvips#2732]
**Describe the bug**
According to https://www.libvips.org/API/current/libvips-draw.html drawing works as follows:
1. call copy
2. draw

While trying to do so I get terrible memory leaks. 

**To Reproduce**
In order to show the behavior I built a minimal (nonsense) example. In my real world application I do not call copy and draw_circle in a loop but it is actually done by the user on mouse click. I also want to copy the image before modifiying it because I push the initial image to my undo buffer in order to be able to undo changes.
```
#include <vips/vips.h>
#include <vector>
#include <vips/vips8>

using namespace std;
using namespace vips;

int main(int argc, char** argv)
{
    VIPS_INIT(argv[0]);
    VImage paintLayer = VImage::new_from_file(argv[1]);
    vector<double> ink;
    ink.push_back(127);
    for (int n = 0; n < 100; ++n)
    {
        paintLayer = paintLayer.copy();
        paintLayer.draw_circle(ink, 10, 10, 10);
    }

    return 0;
}
```
RAM diagnose output of Visual Studio
![grafik](https://user-images.githubusercontent.com/28649121/159326913-1ad8ed41-4469-49d7-afa5-ccd9292505f5.png)
I.e. the example needs more than 10GB of RAM after the loop.

**Expected behavior**
I expect the code to not produce any memory leaks.

**Actual behavior**
Look at the diagram.

**Environment**
 - OS: Windows 10
 - Vips: 8.12

**Comment by jcupitt** [comment]
Hi @MathemanFlo, 

`image = image.copy()` adds a null "copy" node to a pipeline. Pixels are copied between the two images, but they will have different metadata, so you can modify one without changing the other. If you do 100 of these in a row, you'll have a pipeline 100 nodes long (!!).

If you call `.draw_circle()` on a pipeline, it'll allocate a memory area, render the image into it, then draw the circle. This means that every image on your 100 node pipeline will have a separate memory copy of your source image (!!).

I think what you need here is `.copy_memory()`. This allocates ram, renders the image into it, and returns a new image which wraps that memory area. Because it breaks the pipeline, you don't get all the previous images.

I tried:

```C++
/* compile with 
 *
 *      g++ -g -Wall draw.cc `pkg-config vips-cpp --cflags --libs`
 */

#include <vips/vips.h>
#include <vector>
#include <vips/vips8>

using namespace std;
using namespace vips;

int main(int argc, char** argv)
{
    VIPS_INIT(argv[0]);

    VImage paintLayer = VImage::new_from_file(argv[1]);

    vector<double> ink;
    ink.push_back(127);

    for (int n = 0; n < 100000; ++n)
    {
        paintLayer = paintLayer.copy_memory();

        paintLayer.draw_circle(ink, 10, 10, 10);
    }

    return 0;
}
```

And it runs in a steady 50mb on this PC.
