### ISSUE TITLE
JPEG XL: Saving image in float band format fails

### ISSUE THREAD

**Issue by dloebl** [libvips/libvips#2830]
`jxlsave` seems to fail with the following error in case the input image is in the float band format:
`jxlsave: error JxlEncoderSetBasicInfo`

We noticed this behaviour while resizing images with an alpha channel.

**Example image:**
[test.png](https://user-images.githubusercontent.com/34104349/171421127-ded8ee36-3dc4-4bd6-abf8-97ff2cf3880c.png)

**C code:**
```
#include <vips/vips.h>
#include <stdio.h>

int main() {
        VipsImage* in, *thm, *pre, *out;

        VIPS_INIT("test app");

        // load input png
        vips_pngload("test.png",
                &in,
                NULL);

        // resize image
        vips_premultiply(in, &pre, NULL);
        vips_resize(pre, &thm, 0.5, NULL);
        vips_unpremultiply(thm, &out, NULL);

        // save as JPEG XL
        vips_jxlsave(out, "out.jxl", NULL);
        puts(vips_error_buffer());

        vips_shutdown();
        return 0;
}
```

**Environment**
 - OS: MacOS 12.4
 - Vips: v8.13 master
 - libjxl: v0.6.1

**Comment by jcupitt** [comment]
Hi @dloebl, you're right, looks like we need to add a new SAVEABLE enum for scRGB. Let's fix this for 8.13.

**Comment by jcupitt** [comment]
I think 8.13 is already badly delayed, let's punt this to 8.14.

**Comment by jcupitt** [comment]
After asking on libjxl discord, it seems this is the position:

## save strategy

- FLOAT srgb ... convert to 8 bit for write
- scrgb ... write as float, call JxlColorEncodingSetToLinearSRGB(), libjxl wants 0 - 1 so there's no scaling

## load strategy

- char/short data ... as now
- float data ... convert to scRGB, attach the profile, no scaling needed, no need to worry about lionear/nonlinear, since libjxl with synthesise a profile with the correct gamma if necessary

**Comment by jcupitt** [comment]
Fixed with https://github.com/libvips/libvips/commit/9f3860ec22347c8151640d134da4ee9d1e7e2a11

**Comment by lovell** [comment]
@jcupitt It looks like a couple of stray `#define DEBUG` snuck into commit https://github.com/libvips/libvips/commit/9f3860ec22347c8151640d134da4ee9d1e7e2a11
