### ISSUE TITLE
Please keep autotools until next major version

### ISSUE THREAD

**Issue by remicollet** [libvips/libvips#2879]
As it works well ;)

I'm used to consider such a major change to the build system is suitable for a major version, not in a minor one.
(and it is broken for now)

So please keep autotools for now.

**Comment by jcupitt** [comment]
Hi @remicollet, thanks for testing the rc.

I don't think we want to maintain two build systems, so I'm keen to remove autotools as soon as possible.

In my mind, the major version number represents the API the package supports, and that's supposed to be unchanged with this release. The build system is obviously very important for packaging, but isn't generally a big deal for users.

**Comment by kleisauke** [comment]
For reference, GLib also dropped autotools without bumping the major version. See:

> Overview of changes in GLib 2.59.1
==================================
> * Autotools support is gone. (!580)

...

> Overview of changes in GLib 2.59.0
==================================
> * This will be the last development release with autotools support. As our
>  Meson support has been around since 2.56.x, and was used to release tarballs
>  in 2.58.x, the next development release (2.59.1) will drop autotools as used
>  to build GLib. The macros installed for other packages to use will remain.

https://gitlab.gnome.org/GNOME/glib/-/blob/main/NEWS
https://gitlab.gnome.org/GNOME/glib/-/merge_requests/580

**Comment by remicollet** [comment]
I understand...

BTW, among hundreds of packages I maintain
- lot use autotools
- some use cmake
- none use meson ;)

The reason why I'm always reluctant to switch in a new unknown world :p

**Comment by eli-schwartz** [comment]
As a general rule of thumb, I think it's reasonable enough when changing from one build system to another, to have a *transition* state, where one version supports both build systems. You get the opportunity to shake out bugs in the new build system, without leaving people in the lurch if they do run into problems. You can always mark the old build system as deprecated (and possibly print warnings to that effect, even), and a common tactic is to delete the old build system immediately after the next (non-bugfix) release.

But I don't think that you need to wait for a semver major library API/ABI change in order to cycle the build system!

With that in mind, the release notes for the current feature release seem reasonable:
> We’ve settled on [meson](https://mesonbuild.com/) and tintou has very generously done all the work. The old autotools system is still there for this release, but it will be removed for 8.14 and meson will the only one we support.

autotools is available for a transition period of this release, but will be removed in the next release. People are urged to switch over if at all possible, but if they cannot, they can still fall back to autotools for now, while the meson.build gets fixed.

In theory, if it turns out that there are lots of issues with the port, the project maintainers might choose to extend the transition period by the length of another feature release. But even then, that would not necessarily be until a major release... just a feature release.

**Comment by remicollet** [comment]
So 8.14.0 is no more buildable on RHEL-7 (and clones)

`meson.build:1:0: ERROR: Meson version is 0.55.1 but project requires >=0.56`

**Comment by jcupitt** [comment]
I think you will need to do eg. `pip install meson` on older systems.

**Comment by remicollet** [comment]
> I think you will need to do eg. pip install meson on older systems.

Again, not acceptable from a packager PoV.
Package build can only use packages and without internet access.

**Comment by jcupitt** [comment]
Build systems often need extra or updated packages, don't they? For example, you'll very frequently need to update cmake before you can build cmake projects, and packages written in rust seem to always demand an updated toolchain.

**Comment by eli-schwartz** [comment]
I do see it all the time with cmake.

Autotools indeed doesn't have this problem, for two reasons:
- it tends to update about once per decade, so there's nothing to upgrade *to* (unfortunately. Because you then wait for bug fixes for a decade. Which leads into the second reason.)
- it's not a build system, and it's not a build system generator. It's a build system generator generator. You upgrade to the latest version of autotools on the developer machine, and use+rely on its bleeding edge functionality, and then you use it to generate the stuff that runs on RHEL.

...

As far as supported versions of Meson go, that's a project decision, but Meson takes care to provide the tools to give people the ability to mane an informed decision. Personally, when maintaining the WrapDB I try to be very careful and support the oldest versions of Meson I can get away with -- I don't know where people will use it, and the whole point is to integrate with other meson projects which have their own minimum requirements, so it's entirely possible people are still on versions of Ubuntu so old that only Meson 0.45 is available.

That being said, I, on a personal level, will never, ever, ever, EVER pay one bit of attention to the needs of RHEL packagers. I'll pay more attention to Ubuntu 16.04 than I will to the most recent version of RHEL.

This is for one simple reason: I don't have a proprietary RHEL subscription so I can't test on that proprietary OS. Not only that, I cannot even look up what version of Meson is available in RHEL. Even the list of packages is proprietary. It's certainly not available in repology, which is much better at tracking down this information than I am.

But perhaps libvips is in a privileged position to have access to the super secret list of package versions, and can make a more informed decision than I can. :)

**Comment by eli-schwartz** [comment]
> Again, not acceptable from a packager PoV.
Package build can only use packages and without internet access.

Are you unable to backport Meson 0.56 or even 0.61 while you're at it, into a copr or something? Is this package intended for RHEL itself?

**Comment by eli-schwartz** [comment]
In my experience, 0.56 is a.popular cutoff point for projects to choose, because it keeps compatibility with Debian stable as well as oldstable-backports.

Another popular cutoff is 0.53 because it keeps compatibility with Ubuntu 20.04 LTS and the previous LTS would leave you stuck at Meson 0.45

**Comment by remicollet** [comment]
> This is for one simple reason: I don't have a proprietary RHEL subscription

There is "CentOS Stream" and enough "free" clones (Alma, Rocky...)
RHEL is even "free" for developer
https://developers.redhat.com/blog/2016/03/31/no-cost-rhel-developer-subscription-now-available#

> Are you unable to backport Meson 0.56 or even 0.61 while you're at it, into a copr or something? 
Yes, I tried but without success.

And I don't want to spend more time on this, just want to inform you that EL-7 is "no more" supported for vips on my repository.

And BTW, EL-7 is now >8 years old and close to its EOL in 18 months. Everyone wanting "modern features" should upgrade to a modern distro (EL-8 or EL-9)

**Comment by remicollet** [comment]
> I can't test on that proprietary OS

It seems you are confused with OpenSource/Proprietary versus Gratis/Cost ;)

RHEL is a pure OpenSource, nothing Proprietary there,  but support is not Gratis.

**Comment by kleisauke** [comment]
> So 8.14.0 is no more buildable on RHEL-7 (and clones)
> 
> `meson.build:1:0: ERROR: Meson version is 0.55.1 but project requires >=0.56`

I just opened PR https://github.com/libvips/libvips/pull/3257 for this.

**Comment by remicollet** [comment]
> > Are you unable to backport Meson 0.56 or even 0.61 while you're at it, into a copr or something?
> 
> Yes, I tried but without success.

Was finally able to use a private build of meson 0.56.2
So EL-7 support it back (for me, other users are still affected).

**Comment by eli-schwartz** [comment]
> RHEL is even "free" for developer

> It seems you are confused with OpenSource/Proprietary versus Gratis/Cost ;)
> 
> RHEL is a pure OpenSource, nothing Proprietary there, but support is not Gratis.

Free means I can register for it without paying.

Libre (as opposed to proprietary) means I can download it by whatever means necessary (pay for it, register for an account, whatever) and then legally host it myself on a file sharing site for people that don't want to register *or* pay anything.

Can I do that? Has someone done it for me? 

> I just opened PR #3257 for this.

Excellent news, it turns out that given a specific request to modify the project and make it work with a named lower version of Meson, the changes to make that work are trivial and non-burdensome. 🎉

Fantastic resolution.

**Comment by Schamschula** [comment]
Related to the switch to `meson`: I'm trying to update the MacPorts Portfile to version 8.14.1. However I get the following error:

> Main binary: /opt/local/Library/Frameworks/Python.framework/Versions/3.11/bin/python3.11
> Build Options: -Dintrospection=enabled -Dprefix=/opt/local
> Python system: Darwin
> The Meson build system
> Version: 0.64.1
> Source dir: /opt/local/var/macports/build/_Users_marius_Development_MacPorts_ports_graphics_vips/vips/work/vips-8.14.1
> Build dir: /opt/local/var/macports/build/_Users_marius_Development_MacPorts_ports_graphics_vips/vips/work/build
> Build type: native build
> 
> meson.build:1:0: ERROR: Value enabled is not boolean (true or false).

I'm no meson expert, and a search doesn't come up with any useful solutions.

**Comment by jcupitt** [comment]
> -Dintrospection=enabled

I think this needs to be `-Dintrospection=true`. Though that's the default, so you probably don't need to specify it.

**Comment by Schamschula** [comment]
It turns out that I had to use `configure.post_args-append` to manually set `-Dintrospection=true`. Not setting it resulted in the same error, now complaining that the build options are `-Dintrospection=disabled -Dprefix=/opt/local`.

See: https://github.com/macports/macports-ports/commit/2349a691c759a9836e37eefa1c6545739a079eac

**Comment by jcupitt** [comment]
I had a look at gegl (a somewhat similar library) to see how they handle this:

https://github.com/macports/macports-ports/blob/master/graphics/gegl/Portfile

They list the introspection pkgconfig in `depends_lib`:

https://github.com/macports/macports-ports/blob/master/graphics/gegl/Portfile#L51

They use `args-append` for meson options, fwiw, and don't mention introspection:

https://github.com/macports/macports-ports/blob/master/graphics/gegl/Portfile#L94-L97

I don't know if that makes a difference.

**Comment by kleisauke** [comment]
I'll close this issue since no further Meson-related issues have been reported. The introspection option was changed to a feature type with commit https://github.com/libvips/libvips/commit/c0a0630c6bc10420766a6f83adcdd02330fa859d.

Note to self: bump Meson to 0.60 once RHEL 8 reaches its end of life.
https://github.com/libvips/libvips/compare/master...kleisauke:libvips:meson-0.60
