### ISSUE TITLE
[8.13.0-rc1] API/ABI change

### ISSUE THREAD

**Issue by remicollet** [libvips/libvips#2880]
See [API compatibility report for the libvips library between 8.12.2 and 8.13.0-rc1 versions on x86_64](https://rpms.remirepo.net/compat_reports/libvips/8.12.2_to_8.13.0-rc1/compat_report.html#Symbol_Binary_Problems_Low)

At least the struct changes are annoying (__VipsTarget and _VipsTargetCustom)

I think these data types should be made opaque, hidden for library user, as internal functions

**Comment by kleisauke** [comment]
FWIW, I tried to make the `_VipsTarget` / `VipsTarget` struct opaque some time ago, but that failed because the `VIPS_TARGET_PUTC` macro requires some fields to be publicly available.
https://github.com/libvips/libvips/blob/a129476f0febbca8e0df9c6766b141047a20e89c/libvips/include/vips/connection.h#L505-L509
https://github.com/libvips/libvips/blob/a129476f0febbca8e0df9c6766b141047a20e89c/libvips/include/vips/connection.h#L425-L429

Note that PR https://github.com/libvips/libvips/pull/2688 was only done within the Meson build to avoid extra work. Here's an example `abi-compliance-checker` result when building with Meson:
https://kleisauke.nl/compat_reports/vips/8.12.2_to_8.13.0-rc1/compat_report.html
