### ISSUE TITLE
Support background specification during tiff pyramid creation 

### ISSUE THREAD

**Issue by dhandeo** [libvips/libvips#296]
I am using vips for converting images to tiled and pyramidal tiff's for use in digital SlideAtlas-Server. Presently tiffsave errors on background color specification on conversion command line.  

```
vips tiffsave panorama.jpg --tile --pyramid --compression jpeg --tile-width 256 --tile-height 256 --background "255,255,255" output.ptif
```

Will it be possible to support background color that is padded during creation of pyramid ? Some images, especially whole slide images can really look better with white padding. 

I am willing to contribute a patch, but some pointers on what all needs to be done will be really helpful.  

Thank you.

**Comment by jcupitt** [comment]
Hi @dhandeo, I agree, this would be a useful feature. 

`dzsave` has something like this already: it shrinks the image until it fits within a single tile, then centres it, then expands it back to the original size again to get the amount of border to add. Does that sound like the behaviour you want? 

If it does, the code is here:

https://github.com/jcupitt/libvips/blob/master/libvips/foreign/dzsave.c#L1522

That code would need to go into the tiff saver.
 
Alternatively, this is easy to do in Python or C. Just use vips_embed() to enlarge your input image:

http://www.vips.ecs.soton.ac.uk/supported/8.0/doc/html/libvips/libvips-conversion.html#vips-embed

Or I guess you could use `dzsave` instead of a pyramidal tiff.

**Comment by dhandeo** [comment]
For [SlideAtlas](https://github.com/SlideAtlas/SlideAtlas-Server) we either use ptif (pyramidal tiff) as the container format, or store all image tiles in a binary friendly database like mongodb, so using dzsave directly is not suitable right now.

Next, I will go through the code for dzsave, and try to port the feature to tiffsave. Will ask more here if I have questions. 

Also, alignment of the pyramids should also be specified as a parameter. Tiffsave pyramids used to be top-left aligned. I did not know before, but dzsave seems to be aligned at center.

**Comment by jcupitt** [comment]
You can dzsave to a zipfile and store those in the database, I don't know if that would work. You would need a small server add-on to serve tiles from the zipfile rather than the filesystem, of course. 

You can turn off dzsave centring with `centre=false`, I expect you saw.

Good luck!

**Comment by jcupitt** [comment]
Coming back to this again, is the background used for removing alpha, or to pad edges of the image?

If it's for alpha, just set `background=255`. To pad edges, use `embed` to expand the input, then save.

Please reopen if this is still an issue.
