### ISSUE TITLE
Slow 'flip'

### ISSUE THREAD

**Issue by alantudyk** [libvips/libvips#3149]
Test image: https://www.eso.org/public/images/eso2214a/
Compared with https://github.com/alantudyk/xPNG/blob/846d8ad397c8ff6f42c88ef7c030d2aa31c9198f/Mirroring_and_Rotating/tool.c
```
$ vips --vips-version
libvips 8.12.1-Wed Feb  2 14:43:28 UTC 2022

$ /bin/time -f '%U sec' vips flip /tmp/V.ppm /tmp/r.ppm vertical --vips-concurrency=1
0.38 sec
$ /bin/time -f '%U sec' ~/xPNG/Mirroring_and_Rotating/tool --mv /tmp/V.7 /tmp/r.7
0.18 sec

$ /bin/time -f '%U sec' vips flip /tmp/V.ppm /tmp/r.ppm horizontal --vips-concurrency=1
1.03 sec
$ /bin/time -f '%U sec' ~/xPNG/Mirroring_and_Rotating/tool --mh /tmp/V.7 /tmp/r.7
0.35 sec

$ /bin/time -f '%U sec' vips rot /tmp/V.ppm /tmp/r.ppm d180 --vips-concurrency=1
1.95 sec
$ /bin/time -f '%U sec' ~/xPNG/Mirroring_and_Rotating/tool --mvh /tmp/V.7 /tmp/r.7
0.34 sec

$ ll /tmp/V.*
-rw-rw-r-- 1 abc abc 1565682083 ноя  8 12:52 /tmp/V.7  # same as PPM, but with fixed-size non-text header
-rw-rw-r-- 1 abc abc 1565682094 ноя  8 11:38 /tmp/V.ppm
```

**Comment by jcupitt** [comment]
Hi @alantudyk,

Your code is interesting. 

I think they are optimising different things -- the libvips one is trying to be memory efficient and to optimise elapsed (not user) time.  It needs to be able to flip and mirror images much larger than physical memory. It looks like you're optimising user CPU time, is that right?

For a 20k x 20k pixel RGBA image I see:

```
$ /usr/bin/time -f %M:%e ./tool --mv x.7 y.7
1563904:1.85
$ /usr/bin/time -f %M:%e vips flip x.ppm y.ppm vertical --vips-concurrency=1
1213484:1.16
```

So that's peak memuse and elapsed time. I'm a bit surprised memuse is so high for vips, I'll have a look at what the ppm loader is doing. PNG is more reasonable:

```
$ /usr/bin/time -f %M:%e vips flip x.png y.png vertical --vips-concurrency=1
90888:8.63
```

Now it's 90mb of memory. Almost all CPU time is being burned in PNG decode and encode there, of course.

**Comment by jcupitt** [comment]
Ah it's because libvips needs to map the whole ppm read-write, so it has to be backed by a malloc. It's able to map vips images read-only, and to map them in sections, so it's much better:

```
$ vips black x.v 20000 20000 --bands 4
$ /usr/bin/time -f %M:%e vips flip x.v y.v vertical --vips-concurrency=1
50724:1.42
```

**Comment by alantudyk** [comment]
rot d180 uses `memcpy()` to copy a pixel: https://github.com/libvips/libvips/blob/b8a2d26ad923a4166c434e26df9e91afbab1a341/libvips/conversion/rot.c#L210

**Comment by alantudyk** [comment]
Also:
```
$ vips copy x.png x.ppm
$ identify -verbose x.ppm | grep Comment
  Comment: vips2ppm - 2022-11-10T01:28:08.288641+03
```
Can I remove this comment using `vips`?

**Comment by jcupitt** [comment]
> rot d180 uses memcpy() to copy a pixel: 

Ooop! You're right, that's dumb. I've changed it, thanks! Looks like a copy-paste error from 20 years ago :(

**Comment by jcupitt** [comment]
> Can I remove this comment using vips?

Yes, try:

```
vips copy x.jpg x.ppm[strip]
```

The `strip` option makes savers remove all metadata.
