### ISSUE TITLE
[8.14.0] @VIPS_VERSION@ in documentation

### ISSUE THREAD

**Issue by remicollet** [libvips/libvips#3255]
In generated documentation (ex gtk-doc/html/libvips/index.html)

`For libvips @VIPS_VERSION@. The latest version of this documentation can be found on the [libvips website](file:///).`

It seems some substitute command is missing in new build system.

**Comment by jcupitt** [comment]
Hi @remicollet, thanks for the report.

It's doing the substitute, but then using the unsubstituted file to build the docs (!!).

@eli-schwartz could I ping you on this? It's currently doing:

```
version_conf = configuration_data()
version_conf.set('VIPS_VERSION', meson.project_version())
vips_docs = configure_file(
    input: 'libvips-docs.xml.in',
    output: 'libvips-docs.xml',
    configuration: version_conf
)

gnome.gtkdoc('libvips',
    mode: 'none',
    main_xml: 'libvips-docs.xml.in',
    src_dir: [
```

It should obviously be doing something like:

```
gnome.gtkdoc('libvips',
    mode: 'none',
    main_xml: '@0@'.format(vips_docs),
    src_dir: [
```

But then install fails with:

```
Traceback (most recent call last):
  File "/usr/bin/meson", line 38, in <module>
    sys.exit(mesonmain.main())
  File "/usr/lib/python3/dist-packages/mesonbuild/mesonmain.py", line 266, in main
    return run(sys.argv[1:], launcher)
  File "/usr/lib/python3/dist-packages/mesonbuild/mesonmain.py", line 255, in run
    return run_script_command(args[1], args[2:])
  File "/usr/lib/python3/dist-packages/mesonbuild/mesonmain.py", line 215, in run_script_command
    return module.run(script_args)
  File "/usr/lib/python3/dist-packages/mesonbuild/scripts/gtkdochelper.py", line 249, in run
    build_gtkdoc(
  File "/usr/lib/python3/dist-packages/mesonbuild/scripts/gtkdochelper.py", line 126, in build_gtkdoc
    shutil.copyfile(f, os.path.join(abs_out, os.path.basename(f)))
  File "/usr/lib/python3.10/shutil.py", line 254, in copyfile
    with open(src, 'rb') as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: '/home/john/GIT/libvips/doc/doc/libvips-docs.xml'
```

It looks like the gtkdoc helper is adding the source root (`/home/john/GIT/libvips/doc/`) to a local path inside the build area (`doc/libvips-docs.xml`). Is there an easy workaround?

**Comment by kleisauke** [comment]
I just opened PR #3259 for this.

**Comment by jcupitt** [comment]
Nice!

**Comment by eli-schwartz** [comment]
.format() isn't guaranteed to do something meaningful with all possible arguments. It just formats with the python `str()` of the thing you give it -- this works for primitive types and probably does something wrong for built targets.

`configure_file()` happens to return a `files()` object, which has a representation of "the subdir and basename" but doesn't include either the source directory or the build directory. So in this case it's equal to writing the string "doc/libvips-docs.xml", which you don't want (especially since you are repeating "doc/").

The "proper" solution here is either:
- add support to meson for passing built targets as the main xml file, if that isn't currently supported, or
- do what you did, and make it a simple source file that loads a built file
