### ISSUE TITLE
Unable to run "vips dzsave"

### ISSUE THREAD

**Issue by ginalster** [libvips/libvips#3471]
This is for the windows downloaded binary 8.14.2.

D:\vips-dev-8.14.2\bin>vips.exe dzsave
vips.exe: unknown action "dzsave"

This occurs on windows server 2019, windows 10. Interestingly it works on my VM.

Gina

**Comment by ginalster** [comment]
DZSave has been taken out temporarily due to licensing issues. Better if the notice was more obvious.

**Comment by lovell** [comment]
Please see https://github.com/libvips/libvips/issues/3354

**Comment by try-labs** [comment]
```shell
[root@localhost vagrant]# vips dzsave  test.tif dzi_test
vips: unknown action "dzsave"
[root@localhost vagrant]# vips --version
vips-8.13.2-Wed Sep 28 15:28:44 UTC 2022
[root@localhost vagrant]# cat /etc/redhat-release
CentOS Linux release 7.9.2009 (Core)
[root@localhost vagrant]#

```
Unable to run "vips dzsave"

**Comment by jcupitt** [comment]
@try-labs I would guess your libvips has been built without dzsave support. Did you build it yourself?

**Comment by try-labs** [comment]
Directly downloaded installation package
```shell
https://github.com/libvips/libvips/releases/download/v8.14.2/vips-8.14.2.tar.xz
```

**Comment by try-labs** [comment]
@jcupitt  Directly downloaded installation package 
```shell
https://github.com/libvips/libvips/releases/download/v8.14.2/vips-8.14.2.tar.xz
```

**Comment by try-labs** [comment]
```shell
https://github.com/libvips/libvips/archive/refs/tags/v8.13.3.tar.gz
./configure --prefix=/usr/local/libvips
./autogen.sh
make && make install
```

@jcupitt  Do I need to add special parameters for compilation

**Comment by jcupitt** [comment]
I would consider using Remi's libvips RPM:

https://rpms.remirepo.net/enterprise/7/

it would probably be easier than building and maintaining yourself.

If you want to build yourself, I would build the latest stable version, since that's the one we support:

https://github.com/libvips/libvips/releases/tag/v8.14.2

You'll need meson and ninja. There are no specil compile flags, but you will need to install the dependencies you need first. Check the summary at the end of configure.
