### ISSUE TITLE
icc_transform: not able to retain 100% black

### ISSUE THREAD

**Issue by adriaanmeuris** [libvips/libvips#3562]
## Bug report
**Describe the bug**
I exported a CMYK JPG image in Illustrator with embedded profile `U.S. Web Coated (SWOP) v2` profile, with K set to 100%: [swop-100k.jpg.zip](https://github.com/libvips/libvips/files/12013317/swop-100k.jpg.zip)

Opening this file in Illustrator shows the black color to be set to 100%:
<img width="926" alt="screenshot-orig" src="https://github.com/libvips/libvips/assets/16230038/fa1b5b82-92c2-4b43-a31f-f5fd8d437d68">
I'm unable to retain the 100% K when using `vips icc_transform`.

**To Reproduce**
Please find the ICC profile attached: [U.S. Web Coated (SWOP) v2.icc.zip](https://github.com/libvips/libvips/files/12013366/U.S.Web.Coated.SWOP.v2.icc.zip).

Convert the file with following command:
```sh
vips icc_transform swop-100k.jpg swop-100k-VIPS1.jpg "U.S. Web Coated (SWOP) v2.icc"
```
When opening the converted file, `0/0/0/100` is transformed to a kind of rich black `67.84/67.45/65.1/74.12`:
<img width="926" alt="screenshot-vips" src="https://github.com/libvips/libvips/assets/16230038/4f3fb97d-1bb3-48fd-8a37-eb36195b3d73">

**Expected behavior**
As I'm using the same profile the file was created with, I expected to retain the 100K black in the output image.

I tried playing around with parameters of `icc_transform`, without having any effect on the output:
<img width="1075" alt="Screenshot 2023-07-11 at 12 03 19" src="https://github.com/libvips/libvips/assets/16230038/8526a012-d683-4be8-b4ad-b566bd51d69c">

**Actual behavior**
The blacks in the output file are converted to some kind of rich black instead of 100K.

**Environment**
  - System:
    - OS: macOS 13.4.1
    - CPU: (12) arm64 Apple M2 Pro
    - Memory: 62.44 MB / 16.00 GB
    - Shell: 5.9 - /bin/zsh
  - Binaries:
    - vips-8.14.2

**Comment by jcupitt** [comment]
Hi @adriaanmeuris,

I think this is the correct behaviour. CMYK 0/0/0/255 ought to be rendered with some CMY plus a bit of black to darken it, according to your profile. 

You can see what's happing if you import to PCS first:

```
$ vips icc_import swop-100k.jpg x.v 
$ vips getpoint x.v 0 0
22.3529 1.07004 0.0583658 
```

That's the LAB coordinate that your profile specifies for 0/0/0/255 CMYK, it's a darkish black, slightly off neutral, presumably the colour of the pure K ink on that stock. If you now go back to CMYK you get:

```
$ vips icc_export x.v x2.v
$ vips getpoint x2.v 0 0
173 172 166 189 
```

So 189 for K, with a mix of CMY to darken it and set the cast.

Perhaps Illustrator is seeing a transform with identical input and output profiles and simply giving you the source image back again?

**Comment by jcupitt** [comment]
If you need to preserve a K mask, you might be better off running that through a separate path, or treating it as a spot colour.

**Comment by adriaanmeuris** [comment]
@jcupitt I'm no expert in Color Management so I'm thankful for your feedback; your explanation on how the LAB coordinate is specified by the profile was very helpful.

Now regardless of how Illustrator does color transformations, I'm wondering why the 100% K can not be retained when exporting to a new JPEG file using the same profile.


```sh
vips getpoint swop-100k.jpg 0 0
0 0 0 255
vips icc_import --embedded swop-100k.jpg x.v
vips icc_export -o sticker-cmyk-swop.icc x.v swop-100k-VIPS.jpg
vips getpoint swop-100k-VIPS.jpg 0 0
173 172 166 189
```

- The input JPG file was has the `U.S. Web Coated (SWOP) V2.icc` profile attached
- Convert to XYZ using this embedded ICC profile
- Export to a new JPEG file and specifying the same output profile the file was created with (`U.S. Web Coated (SWOP) V2.icc`).

I'm wondering why the second `getpoint` command does not return `0 0 0 255` but returns `173 172 166 189` (which matches the colors I was seeing Illustrator before (67.84% / 67.45% / 65.10% / 74.12%)

This might be an obvious question, but I don't understand why the CMYK values change when going CMYK->Lab->CMYK when the embedded profile used in `icc_import` and the output profile used in `icc_export` are the same?

Any pointers would be greatly appreciated.

**Comment by jcupitt** [comment]
It's to do with something called GCR (Grey Component Replacement).

A colour expressed as CIELAB maps to a single CMY mix, but to *many* CMYK mixes. You can think of the K as being generated in a second pass: any neutral component of a colour (ie. something like C == M == Y) can be replaced by some amount of black instead. Using a black ink means you need less of CMY, which saves money, and also makes the ink lie flatter on the page, since you physically need less of it.

When you make a profile, you set the GCR percentage you'd like. 100% GCR can look odd since you can then get hard transitions in dark areas, so people usually set it to something like 70%. You'd need to look into your SWOP profile to see what GCR it was generated with.

In your specific case, someone made a synthetic CMYK image with 100% K and then attached a standard printers profile. This profile could (almost) never generate 100%, so when you map to LAB and back, you don't get back to where you started from. If you map a second time, you should get your image back again correctly.
