### ISSUE TITLE
VipsDisp 2.5.1 compiles but does not run with VIPS 8.15.0 rc1 release

### ISSUE THREAD

**Issue by vvinycity** [libvips/libvips#3730]
### Discussed in https://github.com/libvips/libvips/discussions/3728

<div type='discussions-op-text'>

<sup>Originally posted by **vvinycity** October 23, 2023</sup>
I compiled VipsDisp 2.5.1 latest sources with new version of libvips (vips-dev-8.15.0 rc1).

The executable does not run and gives an error:
"Procedure entry point g_regex_new could not be located in the dynamic link library libglib-2.0-0.dll"

So, it seems that libglib-2.0-0.dll in 8.15.0 rc1 release is outdated.

Where could I find libglib-2.0-0.dll with "g_regex_new" function defined?

Thank you for your help.</div>

**Comment by vvinycity** [comment]
Please, see below
<img width="1085" alt="g_regex_new_absent" src="https://github.com/libvips/libvips/assets/8726996/ad879982-57f8-4690-b5fb-fb0e0e6a50fd">

**Comment by jcupitt** [comment]
I think the problem is that libvips and gtk both bundle libglib.dll, but they are not bundling the same version, and the libvips one does not have PCRE (perl-compatible regular expressions) enabled, since libvips does not need it.

You could try getting rid of the libglib.dll that came with libvips and using the gtk one instead, but you might hit other compat issues. The best solution is to build everything (all of gtk and all of libvips) from source. But we should talk about this on the vipsdisp tracker.
