### ISSUE TITLE
jxlload.c build failure: JxlDecoderGetICCProfileSize

### ISSUE THREAD

**Issue by Schamschula** [libvips/libvips#3807]
## Bug report

While rebuilding `vips` 8.14.5 under MacPorts due to a linking issue with `libjxl` 0.9.0 I got the following errors:

> /usr/bin/clang -Ilibvips/vips-jxl.so.p -Ilibvips -I../vips-8.14.5/libvips -I. -I../vips-8.14.5 -Ilibvips/include -I../vips-8.14.5/libvips/include -Ilibvips/include/vips -I/opt/local/include/glib-2.0 -I/opt/local/lib/glib-2.0/include -I/opt/local/include/libgsf-1 -I/opt/local/include/libxml2 -I/opt/local/include/libpng16 -I/opt/local/include/webp -I/opt/local/include/pango-1.0 -I/opt/local/include/harfbuzz -I/opt/local/include/fribidi -I/opt/local/include/cairo -I/opt/local/include/pixman-1 -I/opt/local/include/freetype2 -I/opt/local/include/librsvg-2.0 -I/opt/local/include/gdk-pixbuf-2.0 -I/opt/local/include/OpenEXR -I/opt/local/include/Imath -I/opt/local/include/openjpeg-2.5 -I/opt/local/include/orc-0.4 -I/opt/local/include -fdiagnostics-color=always -Wall -Winvalid-pch -std=gnu99 -O0 -g -DDEBUG_LEAK -Werror=pointer-arith -pipe -Os -isysroot/Library/Developer/CommandLineTools/SDKs/MacOSX13.sdk -arch arm64 -isysroot/Library/Developer/CommandLineTools/SDKs/MacOSX13.sdk -DHWY_SHARED_DEFINE -DHAVE_CONFIG_H=1 -pthread -MD -MQ libvips/vips-jxl.so.p/foreign_jxlload.c.o -MF libvips/vips-jxl.so.p/foreign_jxlload.c.o.d -o libvips/vips-jxl.so.p/foreign_jxlload.c.o -c ../vips-8.14.5/libvips/foreign/jxlload.c
> ../vips-8.14.5/libvips/foreign/jxlload.c:566:5: error: too many arguments to function call, expected 3, have 4
>                                 &jxl->icc_size ) ) {
>                                 ^~~~~~~~~~~~~~
> /opt/local/include/jxl/decode.h:775:29: note: 'JxlDecoderGetICCProfileSize' declared here
> JXL_EXPORT JxlDecoderStatus JxlDecoderGetICCProfileSize(
>                             ^
> ../vips-8.14.5/libvips/foreign/jxlload.c:583:20: error: too many arguments to function call, expected 4, have 5
>                                 jxl->icc_data, jxl->icc_size ) ) {
>                                                ^~~~~~~~~~~~~
> /opt/local/include/jxl/decode.h:793:29: note: 'JxlDecoderGetColorAsICCProfile' declared here
> JXL_EXPORT JxlDecoderStatus JxlDecoderGetColorAsICCProfile(
>                             ^
> 2 errors generated.
> 

**To Reproduce**
1. port build vips
2. Use Configuration default
3. See error

**Expected behavior**
Clean build
**Actual behavior**
See error above

**Environment**
macOS 13.6.3 22G436 arm64
Xcode 15.1 15C65

**Additional context**
I removed a now unneeded function argument in both occurrences of `JxlDecoderGetICCProfileSize` in `jxlload.c`.

[libvips-foreign-jxlload copy.c.patch](https://github.com/libvips/libvips/files/13818572/libvips-foreign-jxlload.copy.c.patch)

**Comment by kleisauke** [comment]
This should be fixed in libvips 8.15.1, see: #3774.

**Comment by Schamschula** [comment]
Thanks for the info!

I've updated the port https://github.com/macports/macports-ports/commit/b1540b9428d4151795c6808482af6bdf8de61d65

**Comment by kleisauke** [comment]
Great! I had a quick look at [the port file](https://github.com/macports/macports-ports/blob/b1540b9428d4151795c6808482af6bdf8de61d65/graphics/vips/Portfile) and noticed:
- it depends on hdf5, which is not a direct dependency of libvips (it's a sub-dependency of matio);
- it depends on libtool, which is no longer necessary since we've switched to Meson;
- it depends on both doxygen and gtk-doc, but the `-Ddoxygen=true` and `-Dgtk_doc=true` options are not passed.
- is it build against libheif? Commit https://github.com/macports/macports-ports/commit/b04536ad6852db809131314c34a40a88c22b4ca1 might suggest this, but I don't see it listed as dependency;
- consider removing orc in favor of highway (see https://libvips.org/2023/10/10/What's-new-in-8.15.html#performance-improvements);
- libgsf should be removed in favor of libarchive (see https://libvips.org/2023/10/10/What's-new-in-8.15.html#better-dzsave);

Note that the last 3 points can be detected in Meson by passing `-Dauto_features=enabled`, which will result in build failures if dependencies are missing. [Fedora does this by default](https://lists.fedoraproject.org/archives/list/devel@lists.fedoraproject.org/thread/SVURE6JRDBTFKHJAPFBYRZ62JQ56OLEG/) when building Meson packages.
