### ISSUE TITLE
Unable to use vips-cpp statically with msvc

### ISSUE THREAD

**Issue by Julianiolo** [libvips/libvips#3975]
## Bug report

**Describe the bug**
When compiling the cpp wrapper for libvips it seems to assume a dynamic build (see: [vips8](https://github.com/libvips/libvips/blob/2ad93b3f013e073879832aaf63a3ff14f88eea2c/cplusplus/include/vips/vips8#L43)). However this breaks static builds.
I assume it is supported to use vips-cpp in a static context?, as vips itself works perfectly fine.

**To Reproduce**
Compile libvips on msvc statically, link a program which uses the vips cpp wrapper.

**Expected behavior**
Linking succeds

**Actual behavior**
Symbols are missing, linking fails.

**Environment**
 - OS: Windows 10
 - Vips: 8.15.3

**Additional context**
A dump of the generated `vips-cpp.lib` symbols (via dumpbin) shows the symbols being marked as "External" (should be "Static"):
```
...
C65 00000000 UNDEF  notype       External     | __imp_?get_image@VImage@vips@@QEBAPEAU_VipsImage@@XZ (__declspec(dllimport) public: struct _VipsImage * __cdecl vips::VImage::get_image(void)const )
C66 00000000 UNDEF  notype       External     | __imp_?bands@VImage@vips@@QEBAHXZ (__declspec(dllimport) public: int __cdecl vips::VImage::bands(void)const )
...
```

**Comment by Julianiolo** [comment]
I guess another question is: Why are we using a seperate `VIPS_CPLUSPLUS_API`, when we already have `VIPS_API ` available? I don't think `VIPS_CPLUSPLUS_API` does anything special, right?
[`VIPS_CPLUSPLUS_API`](https://github.com/libvips/libvips/blame/2ad93b3f013e073879832aaf63a3ff14f88eea2c/cplusplus/include/vips/vips8#L48) seems pretty old (~8 years?), while [`VIPS_API`](https://github.com/libvips/libvips/blame/75174cd811ee2256b065c6f6dcfd18de4877eff9/libvips/include/vips/basic.h#L40) seems kinda new (~2 years?). (from what my very brief research revealed)

So is this maybe just some old left over stuff, and we should now use the `VIPS_API`?

**Comment by kleisauke** [comment]
I just opened PR #4033 for this. Any testing would be very helpful.

**Comment by kleisauke** [comment]
... I think the issue was that when building with `--default-library=static` on MSVC that `_VIPS_PUBLIC` was not defined, since that compiler doesn't support the `visibility("default")` attribute.
https://github.com/libvips/libvips/blob/75174cd811ee2256b065c6f6dcfd18de4877eff9/meson.build#L130-L132

Consequently, it falls back to this block:
https://github.com/libvips/libvips/blob/75174cd811ee2256b065c6f6dcfd18de4877eff9/cplusplus/include/vips/vips8#L48-L52

Thus, `VIPS_CPLUSPLUS_API` was always defined as `__declspec(dllexport)` or `__declspec(dllimport)`, depending on whether `VIPS_CPLUSPLUS_EXPORTS` is defined, which isn't an ideal approach for static builds.
