### ISSUE TITLE
vipsthumbnail fails with piped stdin, but not with stdin as file descriptor

### ISSUE THREAD

**Issue by martoche** [libvips/libvips#4303]
## Bug report

**Describe the bug**
The `vipsthumbnail` fails with a piped stdin, but not with stdin as a file descriptor.

In consequence, `vipsthumbnail` is not very friendly to use when being exec'd from another program that passes the data directly from memory. Eg: a webserver that has an image in memory and wants to make a thumbnail.

**To Reproduce**
Run the following command in a terminal:
```
$ cat test.heic | vipsthumbnail stdin > test.jpg

(vipsthumbnail:20719): VIPS-WARNING **: 17:20:55.771: error in tile 0 x 0
vipsthumbnail: unable to thumbnail stdin
source: bad seek to 461
heif: Invalid input: Unspecified: Error setting input file position (2.0)
```

**Expected behavior**
I expected the above command to work, just like this one works:
```
$ vipsthumbnail stdin < test.heic > test.jpg
```

**Actual behavior**
An error is printed in stderr, see above.

**Environment**
(please complete the following information)
 - OS: macOS 13.7.1
 - Vips: 8.16.0

**Comment by jcupitt** [comment]
Hi @martoche, 

This happens for formats which need to be able to seek their input, like HEIC and TIFF. You'll find thumbnail works for all JPG images (no seeking required for this format):

```
$ cat test.jpg | vipsthumbnail stdin -o .jpg > x.jpg
```

If you try this with something like HEIC, libvips will see the seek and automatically switch to buffering the input image in memory. However, this is a security risk, since an attacker could send unbounded data down the pipe and fill server ram.

With small images, this should just work:

```
$ cat image1.heic | vipsthumbnail stdin -o .jpg > x.jpg
```

With very large images (over 1gb I think) you will need to set `VIPS_PIPE_READ_LIMIT`, perhaps:

```
$ VIPS_PIPE_READ_LIMIT=10gb cat image1.heic | vipsthumbnail stdin -o .jpg > x.jpg
```
